FROM golang:1.26-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/worker ./cmd/worker/main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/worker .

EXPOSE 9090
CMD ["./worker"]