// Code generated by ent, DO NOT EDIT.

package vminventory

import (
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldName, v))
}

// CPU applies equality check predicate on the "cpu" field. It's identical to CPUEQ.
func CPU(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldCPU, v))
}

// Memory applies equality check predicate on the "memory" field. It's identical to MemoryEQ.
func Memory(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldMemory, v))
}

// PowerState applies equality check predicate on the "power_state" field. It's identical to PowerStateEQ.
func PowerState(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldPowerState, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldContainsFold(FieldName, v))
}

// CPUEQ applies the EQ predicate on the "cpu" field.
func CPUEQ(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldCPU, v))
}

// CPUNEQ applies the NEQ predicate on the "cpu" field.
func CPUNEQ(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNEQ(FieldCPU, v))
}

// CPUIn applies the In predicate on the "cpu" field.
func CPUIn(vs ...int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldIn(FieldCPU, vs...))
}

// CPUNotIn applies the NotIn predicate on the "cpu" field.
func CPUNotIn(vs ...int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNotIn(FieldCPU, vs...))
}

// CPUGT applies the GT predicate on the "cpu" field.
func CPUGT(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGT(FieldCPU, v))
}

// CPUGTE applies the GTE predicate on the "cpu" field.
func CPUGTE(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGTE(FieldCPU, v))
}

// CPULT applies the LT predicate on the "cpu" field.
func CPULT(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLT(FieldCPU, v))
}

// CPULTE applies the LTE predicate on the "cpu" field.
func CPULTE(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLTE(FieldCPU, v))
}

// MemoryEQ applies the EQ predicate on the "memory" field.
func MemoryEQ(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldMemory, v))
}

// MemoryNEQ applies the NEQ predicate on the "memory" field.
func MemoryNEQ(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNEQ(FieldMemory, v))
}

// MemoryIn applies the In predicate on the "memory" field.
func MemoryIn(vs ...int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldIn(FieldMemory, vs...))
}

// MemoryNotIn applies the NotIn predicate on the "memory" field.
func MemoryNotIn(vs ...int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNotIn(FieldMemory, vs...))
}

// MemoryGT applies the GT predicate on the "memory" field.
func MemoryGT(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGT(FieldMemory, v))
}

// MemoryGTE applies the GTE predicate on the "memory" field.
func MemoryGTE(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGTE(FieldMemory, v))
}

// MemoryLT applies the LT predicate on the "memory" field.
func MemoryLT(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLT(FieldMemory, v))
}

// MemoryLTE applies the LTE predicate on the "memory" field.
func MemoryLTE(v int) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLTE(FieldMemory, v))
}

// PowerStateEQ applies the EQ predicate on the "power_state" field.
func PowerStateEQ(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldPowerState, v))
}

// PowerStateNEQ applies the NEQ predicate on the "power_state" field.
func PowerStateNEQ(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNEQ(FieldPowerState, v))
}

// PowerStateIn applies the In predicate on the "power_state" field.
func PowerStateIn(vs ...string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldIn(FieldPowerState, vs...))
}

// PowerStateNotIn applies the NotIn predicate on the "power_state" field.
func PowerStateNotIn(vs ...string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNotIn(FieldPowerState, vs...))
}

// PowerStateGT applies the GT predicate on the "power_state" field.
func PowerStateGT(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGT(FieldPowerState, v))
}

// PowerStateGTE applies the GTE predicate on the "power_state" field.
func PowerStateGTE(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGTE(FieldPowerState, v))
}

// PowerStateLT applies the LT predicate on the "power_state" field.
func PowerStateLT(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLT(FieldPowerState, v))
}

// PowerStateLTE applies the LTE predicate on the "power_state" field.
func PowerStateLTE(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLTE(FieldPowerState, v))
}

// PowerStateContains applies the Contains predicate on the "power_state" field.
func PowerStateContains(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldContains(FieldPowerState, v))
}

// PowerStateHasPrefix applies the HasPrefix predicate on the "power_state" field.
func PowerStateHasPrefix(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldHasPrefix(FieldPowerState, v))
}

// PowerStateHasSuffix applies the HasSuffix predicate on the "power_state" field.
func PowerStateHasSuffix(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldHasSuffix(FieldPowerState, v))
}

// PowerStateEqualFold applies the EqualFold predicate on the "power_state" field.
func PowerStateEqualFold(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEqualFold(FieldPowerState, v))
}

// PowerStateContainsFold applies the ContainsFold predicate on the "power_state" field.
func PowerStateContainsFold(v string) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldContainsFold(FieldPowerState, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VMInventory {
	return predicate.VMInventory(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VMInventory) predicate.VMInventory {
	return predicate.VMInventory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VMInventory) predicate.VMInventory {
	return predicate.VMInventory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VMInventory) predicate.VMInventory {
	return predicate.VMInventory(sql.NotPredicates(p))
}
