// Code generated by ent, DO NOT EDIT.

package auditrun

import (
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLTE(FieldID, id))
}

// AuditID applies equality check predicate on the "audit_id" field. It's identical to AuditIDEQ.
func AuditID(v int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldAuditID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldStatus, v))
}

// ActualValue applies equality check predicate on the "actual_value" field. It's identical to ActualValueEQ.
func ActualValue(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldActualValue, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldErrorMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// AuditIDEQ applies the EQ predicate on the "audit_id" field.
func AuditIDEQ(v int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldAuditID, v))
}

// AuditIDNEQ applies the NEQ predicate on the "audit_id" field.
func AuditIDNEQ(v int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldAuditID, v))
}

// AuditIDIn applies the In predicate on the "audit_id" field.
func AuditIDIn(vs ...int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldAuditID, vs...))
}

// AuditIDNotIn applies the NotIn predicate on the "audit_id" field.
func AuditIDNotIn(vs ...int) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldAuditID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldContainsFold(FieldStatus, v))
}

// ActualValueEQ applies the EQ predicate on the "actual_value" field.
func ActualValueEQ(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldActualValue, v))
}

// ActualValueNEQ applies the NEQ predicate on the "actual_value" field.
func ActualValueNEQ(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldActualValue, v))
}

// ActualValueIn applies the In predicate on the "actual_value" field.
func ActualValueIn(vs ...string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldActualValue, vs...))
}

// ActualValueNotIn applies the NotIn predicate on the "actual_value" field.
func ActualValueNotIn(vs ...string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldActualValue, vs...))
}

// ActualValueGT applies the GT predicate on the "actual_value" field.
func ActualValueGT(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGT(FieldActualValue, v))
}

// ActualValueGTE applies the GTE predicate on the "actual_value" field.
func ActualValueGTE(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGTE(FieldActualValue, v))
}

// ActualValueLT applies the LT predicate on the "actual_value" field.
func ActualValueLT(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLT(FieldActualValue, v))
}

// ActualValueLTE applies the LTE predicate on the "actual_value" field.
func ActualValueLTE(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLTE(FieldActualValue, v))
}

// ActualValueContains applies the Contains predicate on the "actual_value" field.
func ActualValueContains(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldContains(FieldActualValue, v))
}

// ActualValueHasPrefix applies the HasPrefix predicate on the "actual_value" field.
func ActualValueHasPrefix(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldHasPrefix(FieldActualValue, v))
}

// ActualValueHasSuffix applies the HasSuffix predicate on the "actual_value" field.
func ActualValueHasSuffix(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldHasSuffix(FieldActualValue, v))
}

// ActualValueIsNil applies the IsNil predicate on the "actual_value" field.
func ActualValueIsNil() predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIsNull(FieldActualValue))
}

// ActualValueNotNil applies the NotNil predicate on the "actual_value" field.
func ActualValueNotNil() predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotNull(FieldActualValue))
}

// ActualValueEqualFold applies the EqualFold predicate on the "actual_value" field.
func ActualValueEqualFold(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEqualFold(FieldActualValue, v))
}

// ActualValueContainsFold applies the ContainsFold predicate on the "actual_value" field.
func ActualValueContainsFold(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldContainsFold(FieldActualValue, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuditRun {
	return predicate.AuditRun(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAudit applies the HasEdge predicate on the "audit" edge.
func HasAudit() predicate.AuditRun {
	return predicate.AuditRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuditTable, AuditColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditWith applies the HasEdge predicate on the "audit" edge with a given conditions (other predicates).
func HasAuditWith(preds ...predicate.Audit) predicate.AuditRun {
	return predicate.AuditRun(func(s *sql.Selector) {
		step := newAuditStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIssues applies the HasEdge predicate on the "issues" edge.
func HasIssues() predicate.AuditRun {
	return predicate.AuditRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IssuesTable, IssuesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIssuesWith applies the HasEdge predicate on the "issues" edge with a given conditions (other predicates).
func HasIssuesWith(preds ...predicate.Issue) predicate.AuditRun {
	return predicate.AuditRun(func(s *sql.Selector) {
		step := newIssuesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditRun) predicate.AuditRun {
	return predicate.AuditRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditRun) predicate.AuditRun {
	return predicate.AuditRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditRun) predicate.AuditRun {
	return predicate.AuditRun(sql.NotPredicates(p))
}
