// Code generated by ent, DO NOT EDIT.

package policyrun

import (
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLTE(FieldID, id))
}

// PolicyID applies equality check predicate on the "policy_id" field. It's identical to PolicyIDEQ.
func PolicyID(v int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldPolicyID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldStatus, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldCompletedAt, v))
}

// PolicyIDEQ applies the EQ predicate on the "policy_id" field.
func PolicyIDEQ(v int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldPolicyID, v))
}

// PolicyIDNEQ applies the NEQ predicate on the "policy_id" field.
func PolicyIDNEQ(v int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNEQ(FieldPolicyID, v))
}

// PolicyIDIn applies the In predicate on the "policy_id" field.
func PolicyIDIn(vs ...int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldIn(FieldPolicyID, vs...))
}

// PolicyIDNotIn applies the NotIn predicate on the "policy_id" field.
func PolicyIDNotIn(vs ...int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNotIn(FieldPolicyID, vs...))
}

// PolicyIDGT applies the GT predicate on the "policy_id" field.
func PolicyIDGT(v int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGT(FieldPolicyID, v))
}

// PolicyIDGTE applies the GTE predicate on the "policy_id" field.
func PolicyIDGTE(v int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGTE(FieldPolicyID, v))
}

// PolicyIDLT applies the LT predicate on the "policy_id" field.
func PolicyIDLT(v int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLT(FieldPolicyID, v))
}

// PolicyIDLTE applies the LTE predicate on the "policy_id" field.
func PolicyIDLTE(v int) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLTE(FieldPolicyID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldContainsFold(FieldStatus, v))
}

// AuditRunIdsIsNil applies the IsNil predicate on the "audit_run_ids" field.
func AuditRunIdsIsNil() predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldIsNull(FieldAuditRunIds))
}

// AuditRunIdsNotNil applies the NotNil predicate on the "audit_run_ids" field.
func AuditRunIdsNotNil() predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNotNull(FieldAuditRunIds))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.PolicyRun {
	return predicate.PolicyRun(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PolicyRun) predicate.PolicyRun {
	return predicate.PolicyRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PolicyRun) predicate.PolicyRun {
	return predicate.PolicyRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PolicyRun) predicate.PolicyRun {
	return predicate.PolicyRun(sql.NotPredicates(p))
}
