// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditsColumns holds the columns for the "audits" table.
	AuditsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "sql_query", Type: field.TypeString},
		{Name: "expected_type", Type: field.TypeString},
		{Name: "expected_value", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuditsTable holds the schema information for the "audits" table.
	AuditsTable = &schema.Table{
		Name:       "audits",
		Columns:    AuditsColumns,
		PrimaryKey: []*schema.Column{AuditsColumns[0]},
	}
	// AuditRunsColumns holds the columns for the "audit_runs" table.
	AuditRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeString},
		{Name: "actual_value", Type: field.TypeString, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "audit_id", Type: field.TypeInt},
	}
	// AuditRunsTable holds the schema information for the "audit_runs" table.
	AuditRunsTable = &schema.Table{
		Name:       "audit_runs",
		Columns:    AuditRunsColumns,
		PrimaryKey: []*schema.Column{AuditRunsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_runs_audits_runs",
				Columns:    []*schema.Column{AuditRunsColumns[8]},
				RefColumns: []*schema.Column{AuditsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// IssuesColumns holds the columns for the "issues" table.
	IssuesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "expected_value", Type: field.TypeString},
		{Name: "actual_value", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "audit_id", Type: field.TypeInt},
		{Name: "audit_run_id", Type: field.TypeInt},
	}
	// IssuesTable holds the schema information for the "issues" table.
	IssuesTable = &schema.Table{
		Name:       "issues",
		Columns:    IssuesColumns,
		PrimaryKey: []*schema.Column{IssuesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "issues_audits_issues",
				Columns:    []*schema.Column{IssuesColumns[6]},
				RefColumns: []*schema.Column{AuditsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "issues_audit_runs_issues",
				Columns:    []*schema.Column{IssuesColumns[7]},
				RefColumns: []*schema.Column{AuditRunsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// VMInventoryColumns holds the columns for the "vm_inventory" table.
	VMInventoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "cpu", Type: field.TypeInt},
		{Name: "memory", Type: field.TypeInt},
		{Name: "power_state", Type: field.TypeString, Default: "on"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VMInventoryTable holds the schema information for the "vm_inventory" table.
	VMInventoryTable = &schema.Table{
		Name:       "vm_inventory",
		Columns:    VMInventoryColumns,
		PrimaryKey: []*schema.Column{VMInventoryColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditsTable,
		AuditRunsTable,
		IssuesTable,
		VMInventoryTable,
	}
)

func init() {
	AuditRunsTable.ForeignKeys[0].RefTable = AuditsTable
	IssuesTable.ForeignKeys[0].RefTable = AuditsTable
	IssuesTable.ForeignKeys[1].RefTable = AuditRunsTable
	VMInventoryTable.Annotation = &entsql.Annotation{
		Table: "vm_inventory",
	}
}
