// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"security-central/ent/auditrun"
	"security-central/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditRunDelete is the builder for deleting a AuditRun entity.
type AuditRunDelete struct {
	config
	hooks    []Hook
	mutation *AuditRunMutation
}

// Where appends a list predicates to the AuditRunDelete builder.
func (_d *AuditRunDelete) Where(ps ...predicate.AuditRun) *AuditRunDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuditRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuditRunDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuditRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(auditrun.Table, sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuditRunDeleteOne is the builder for deleting a single AuditRun entity.
type AuditRunDeleteOne struct {
	_d *AuditRunDelete
}

// Where appends a list predicates to the AuditRunDelete builder.
func (_d *AuditRunDeleteOne) Where(ps ...predicate.AuditRun) *AuditRunDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuditRunDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{auditrun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuditRunDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
