// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/audit"
	"security-central/ent/auditrun"
	"security-central/ent/issue"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditCreate is the builder for creating a Audit entity.
type AuditCreate struct {
	config
	mutation *AuditMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AuditCreate) SetName(v string) *AuditCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSQLQuery sets the "sql_query" field.
func (_c *AuditCreate) SetSQLQuery(v string) *AuditCreate {
	_c.mutation.SetSQLQuery(v)
	return _c
}

// SetExpectedType sets the "expected_type" field.
func (_c *AuditCreate) SetExpectedType(v string) *AuditCreate {
	_c.mutation.SetExpectedType(v)
	return _c
}

// SetExpectedValue sets the "expected_value" field.
func (_c *AuditCreate) SetExpectedValue(v string) *AuditCreate {
	_c.mutation.SetExpectedValue(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditCreate) SetCreatedAt(v time.Time) *AuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditCreate) SetNillableCreatedAt(v *time.Time) *AuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuditCreate) SetUpdatedAt(v time.Time) *AuditCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuditCreate) SetNillableUpdatedAt(v *time.Time) *AuditCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddRunIDs adds the "runs" edge to the AuditRun entity by IDs.
func (_c *AuditCreate) AddRunIDs(ids ...int) *AuditCreate {
	_c.mutation.AddRunIDs(ids...)
	return _c
}

// AddRuns adds the "runs" edges to the AuditRun entity.
func (_c *AuditCreate) AddRuns(v ...*AuditRun) *AuditCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRunIDs(ids...)
}

// AddIssueIDs adds the "issues" edge to the Issue entity by IDs.
func (_c *AuditCreate) AddIssueIDs(ids ...int) *AuditCreate {
	_c.mutation.AddIssueIDs(ids...)
	return _c
}

// AddIssues adds the "issues" edges to the Issue entity.
func (_c *AuditCreate) AddIssues(v ...*Issue) *AuditCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIssueIDs(ids...)
}

// Mutation returns the AuditMutation object of the builder.
func (_c *AuditCreate) Mutation() *AuditMutation {
	return _c.mutation
}

// Save creates the Audit in the database.
func (_c *AuditCreate) Save(ctx context.Context) (*Audit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditCreate) SaveX(ctx context.Context) *Audit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := audit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := audit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Audit.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := audit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Audit.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SQLQuery(); !ok {
		return &ValidationError{Name: "sql_query", err: errors.New(`ent: missing required field "Audit.sql_query"`)}
	}
	if v, ok := _c.mutation.SQLQuery(); ok {
		if err := audit.SQLQueryValidator(v); err != nil {
			return &ValidationError{Name: "sql_query", err: fmt.Errorf(`ent: validator failed for field "Audit.sql_query": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpectedType(); !ok {
		return &ValidationError{Name: "expected_type", err: errors.New(`ent: missing required field "Audit.expected_type"`)}
	}
	if v, ok := _c.mutation.ExpectedType(); ok {
		if err := audit.ExpectedTypeValidator(v); err != nil {
			return &ValidationError{Name: "expected_type", err: fmt.Errorf(`ent: validator failed for field "Audit.expected_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpectedValue(); !ok {
		return &ValidationError{Name: "expected_value", err: errors.New(`ent: missing required field "Audit.expected_value"`)}
	}
	if v, ok := _c.mutation.ExpectedValue(); ok {
		if err := audit.ExpectedValueValidator(v); err != nil {
			return &ValidationError{Name: "expected_value", err: fmt.Errorf(`ent: validator failed for field "Audit.expected_value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Audit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Audit.updated_at"`)}
	}
	return nil
}

func (_c *AuditCreate) sqlSave(ctx context.Context) (*Audit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditCreate) createSpec() (*Audit, *sqlgraph.CreateSpec) {
	var (
		_node = &Audit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(audit.Table, sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(audit.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SQLQuery(); ok {
		_spec.SetField(audit.FieldSQLQuery, field.TypeString, value)
		_node.SQLQuery = value
	}
	if value, ok := _c.mutation.ExpectedType(); ok {
		_spec.SetField(audit.FieldExpectedType, field.TypeString, value)
		_node.ExpectedType = value
	}
	if value, ok := _c.mutation.ExpectedValue(); ok {
		_spec.SetField(audit.FieldExpectedValue, field.TypeString, value)
		_node.ExpectedValue = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(audit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(audit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.RunsTable,
			Columns: []string{audit.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.IssuesTable,
			Columns: []string{audit.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuditCreateBulk is the builder for creating many Audit entities in bulk.
type AuditCreateBulk struct {
	config
	err      error
	builders []*AuditCreate
}

// Save creates the Audit entities in the database.
func (_c *AuditCreateBulk) Save(ctx context.Context) ([]*Audit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Audit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditCreateBulk) SaveX(ctx context.Context) []*Audit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
