// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/audit"
	"security-central/ent/auditrun"
	"security-central/ent/issue"
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditUpdate is the builder for updating Audit entities.
type AuditUpdate struct {
	config
	hooks    []Hook
	mutation *AuditMutation
}

// Where appends a list predicates to the AuditUpdate builder.
func (_u *AuditUpdate) Where(ps ...predicate.Audit) *AuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AuditUpdate) SetName(v string) *AuditUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableName(v *string) *AuditUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSQLQuery sets the "sql_query" field.
func (_u *AuditUpdate) SetSQLQuery(v string) *AuditUpdate {
	_u.mutation.SetSQLQuery(v)
	return _u
}

// SetNillableSQLQuery sets the "sql_query" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableSQLQuery(v *string) *AuditUpdate {
	if v != nil {
		_u.SetSQLQuery(*v)
	}
	return _u
}

// SetExpectedType sets the "expected_type" field.
func (_u *AuditUpdate) SetExpectedType(v string) *AuditUpdate {
	_u.mutation.SetExpectedType(v)
	return _u
}

// SetNillableExpectedType sets the "expected_type" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableExpectedType(v *string) *AuditUpdate {
	if v != nil {
		_u.SetExpectedType(*v)
	}
	return _u
}

// SetExpectedValue sets the "expected_value" field.
func (_u *AuditUpdate) SetExpectedValue(v string) *AuditUpdate {
	_u.mutation.SetExpectedValue(v)
	return _u
}

// SetNillableExpectedValue sets the "expected_value" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableExpectedValue(v *string) *AuditUpdate {
	if v != nil {
		_u.SetExpectedValue(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditUpdate) SetCreatedAt(v time.Time) *AuditUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableCreatedAt(v *time.Time) *AuditUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuditUpdate) SetUpdatedAt(v time.Time) *AuditUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRunIDs adds the "runs" edge to the AuditRun entity by IDs.
func (_u *AuditUpdate) AddRunIDs(ids ...int) *AuditUpdate {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the AuditRun entity.
func (_u *AuditUpdate) AddRuns(v ...*AuditRun) *AuditUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// AddIssueIDs adds the "issues" edge to the Issue entity by IDs.
func (_u *AuditUpdate) AddIssueIDs(ids ...int) *AuditUpdate {
	_u.mutation.AddIssueIDs(ids...)
	return _u
}

// AddIssues adds the "issues" edges to the Issue entity.
func (_u *AuditUpdate) AddIssues(v ...*Issue) *AuditUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIssueIDs(ids...)
}

// Mutation returns the AuditMutation object of the builder.
func (_u *AuditUpdate) Mutation() *AuditMutation {
	return _u.mutation
}

// ClearRuns clears all "runs" edges to the AuditRun entity.
func (_u *AuditUpdate) ClearRuns() *AuditUpdate {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to AuditRun entities by IDs.
func (_u *AuditUpdate) RemoveRunIDs(ids ...int) *AuditUpdate {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to AuditRun entities.
func (_u *AuditUpdate) RemoveRuns(v ...*AuditRun) *AuditUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// ClearIssues clears all "issues" edges to the Issue entity.
func (_u *AuditUpdate) ClearIssues() *AuditUpdate {
	_u.mutation.ClearIssues()
	return _u
}

// RemoveIssueIDs removes the "issues" edge to Issue entities by IDs.
func (_u *AuditUpdate) RemoveIssueIDs(ids ...int) *AuditUpdate {
	_u.mutation.RemoveIssueIDs(ids...)
	return _u
}

// RemoveIssues removes "issues" edges to Issue entities.
func (_u *AuditUpdate) RemoveIssues(v ...*Issue) *AuditUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIssueIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuditUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := audit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := audit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Audit.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SQLQuery(); ok {
		if err := audit.SQLQueryValidator(v); err != nil {
			return &ValidationError{Name: "sql_query", err: fmt.Errorf(`ent: validator failed for field "Audit.sql_query": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpectedType(); ok {
		if err := audit.ExpectedTypeValidator(v); err != nil {
			return &ValidationError{Name: "expected_type", err: fmt.Errorf(`ent: validator failed for field "Audit.expected_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpectedValue(); ok {
		if err := audit.ExpectedValueValidator(v); err != nil {
			return &ValidationError{Name: "expected_value", err: fmt.Errorf(`ent: validator failed for field "Audit.expected_value": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(audit.Table, audit.Columns, sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(audit.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SQLQuery(); ok {
		_spec.SetField(audit.FieldSQLQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpectedType(); ok {
		_spec.SetField(audit.FieldExpectedType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpectedValue(); ok {
		_spec.SetField(audit.FieldExpectedValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(audit.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(audit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.RunsTable,
			Columns: []string{audit.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.RunsTable,
			Columns: []string{audit.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.RunsTable,
			Columns: []string{audit.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.IssuesTable,
			Columns: []string{audit.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIssuesIDs(); len(nodes) > 0 && !_u.mutation.IssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.IssuesTable,
			Columns: []string{audit.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.IssuesTable,
			Columns: []string{audit.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditUpdateOne is the builder for updating a single Audit entity.
type AuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditMutation
}

// SetName sets the "name" field.
func (_u *AuditUpdateOne) SetName(v string) *AuditUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableName(v *string) *AuditUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSQLQuery sets the "sql_query" field.
func (_u *AuditUpdateOne) SetSQLQuery(v string) *AuditUpdateOne {
	_u.mutation.SetSQLQuery(v)
	return _u
}

// SetNillableSQLQuery sets the "sql_query" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableSQLQuery(v *string) *AuditUpdateOne {
	if v != nil {
		_u.SetSQLQuery(*v)
	}
	return _u
}

// SetExpectedType sets the "expected_type" field.
func (_u *AuditUpdateOne) SetExpectedType(v string) *AuditUpdateOne {
	_u.mutation.SetExpectedType(v)
	return _u
}

// SetNillableExpectedType sets the "expected_type" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableExpectedType(v *string) *AuditUpdateOne {
	if v != nil {
		_u.SetExpectedType(*v)
	}
	return _u
}

// SetExpectedValue sets the "expected_value" field.
func (_u *AuditUpdateOne) SetExpectedValue(v string) *AuditUpdateOne {
	_u.mutation.SetExpectedValue(v)
	return _u
}

// SetNillableExpectedValue sets the "expected_value" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableExpectedValue(v *string) *AuditUpdateOne {
	if v != nil {
		_u.SetExpectedValue(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditUpdateOne) SetCreatedAt(v time.Time) *AuditUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableCreatedAt(v *time.Time) *AuditUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuditUpdateOne) SetUpdatedAt(v time.Time) *AuditUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRunIDs adds the "runs" edge to the AuditRun entity by IDs.
func (_u *AuditUpdateOne) AddRunIDs(ids ...int) *AuditUpdateOne {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the AuditRun entity.
func (_u *AuditUpdateOne) AddRuns(v ...*AuditRun) *AuditUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// AddIssueIDs adds the "issues" edge to the Issue entity by IDs.
func (_u *AuditUpdateOne) AddIssueIDs(ids ...int) *AuditUpdateOne {
	_u.mutation.AddIssueIDs(ids...)
	return _u
}

// AddIssues adds the "issues" edges to the Issue entity.
func (_u *AuditUpdateOne) AddIssues(v ...*Issue) *AuditUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIssueIDs(ids...)
}

// Mutation returns the AuditMutation object of the builder.
func (_u *AuditUpdateOne) Mutation() *AuditMutation {
	return _u.mutation
}

// ClearRuns clears all "runs" edges to the AuditRun entity.
func (_u *AuditUpdateOne) ClearRuns() *AuditUpdateOne {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to AuditRun entities by IDs.
func (_u *AuditUpdateOne) RemoveRunIDs(ids ...int) *AuditUpdateOne {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to AuditRun entities.
func (_u *AuditUpdateOne) RemoveRuns(v ...*AuditRun) *AuditUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// ClearIssues clears all "issues" edges to the Issue entity.
func (_u *AuditUpdateOne) ClearIssues() *AuditUpdateOne {
	_u.mutation.ClearIssues()
	return _u
}

// RemoveIssueIDs removes the "issues" edge to Issue entities by IDs.
func (_u *AuditUpdateOne) RemoveIssueIDs(ids ...int) *AuditUpdateOne {
	_u.mutation.RemoveIssueIDs(ids...)
	return _u
}

// RemoveIssues removes "issues" edges to Issue entities.
func (_u *AuditUpdateOne) RemoveIssues(v ...*Issue) *AuditUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIssueIDs(ids...)
}

// Where appends a list predicates to the AuditUpdate builder.
func (_u *AuditUpdateOne) Where(ps ...predicate.Audit) *AuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditUpdateOne) Select(field string, fields ...string) *AuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Audit entity.
func (_u *AuditUpdateOne) Save(ctx context.Context) (*Audit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditUpdateOne) SaveX(ctx context.Context) *Audit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuditUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := audit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := audit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Audit.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SQLQuery(); ok {
		if err := audit.SQLQueryValidator(v); err != nil {
			return &ValidationError{Name: "sql_query", err: fmt.Errorf(`ent: validator failed for field "Audit.sql_query": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpectedType(); ok {
		if err := audit.ExpectedTypeValidator(v); err != nil {
			return &ValidationError{Name: "expected_type", err: fmt.Errorf(`ent: validator failed for field "Audit.expected_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpectedValue(); ok {
		if err := audit.ExpectedValueValidator(v); err != nil {
			return &ValidationError{Name: "expected_value", err: fmt.Errorf(`ent: validator failed for field "Audit.expected_value": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditUpdateOne) sqlSave(ctx context.Context) (_node *Audit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(audit.Table, audit.Columns, sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Audit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, audit.FieldID)
		for _, f := range fields {
			if !audit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != audit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(audit.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SQLQuery(); ok {
		_spec.SetField(audit.FieldSQLQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpectedType(); ok {
		_spec.SetField(audit.FieldExpectedType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpectedValue(); ok {
		_spec.SetField(audit.FieldExpectedValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(audit.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(audit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.RunsTable,
			Columns: []string{audit.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.RunsTable,
			Columns: []string{audit.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.RunsTable,
			Columns: []string{audit.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.IssuesTable,
			Columns: []string{audit.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIssuesIDs(); len(nodes) > 0 && !_u.mutation.IssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.IssuesTable,
			Columns: []string{audit.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   audit.IssuesTable,
			Columns: []string{audit.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Audit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
