// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/audit"
	"security-central/ent/auditrun"
	"security-central/ent/issue"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditRunCreate is the builder for creating a AuditRun entity.
type AuditRunCreate struct {
	config
	mutation *AuditRunMutation
	hooks    []Hook
}

// SetAuditID sets the "audit_id" field.
func (_c *AuditRunCreate) SetAuditID(v int) *AuditRunCreate {
	_c.mutation.SetAuditID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AuditRunCreate) SetStatus(v string) *AuditRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetActualValue sets the "actual_value" field.
func (_c *AuditRunCreate) SetActualValue(v string) *AuditRunCreate {
	_c.mutation.SetActualValue(v)
	return _c
}

// SetNillableActualValue sets the "actual_value" field if the given value is not nil.
func (_c *AuditRunCreate) SetNillableActualValue(v *string) *AuditRunCreate {
	if v != nil {
		_c.SetActualValue(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AuditRunCreate) SetErrorMessage(v string) *AuditRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AuditRunCreate) SetNillableErrorMessage(v *string) *AuditRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AuditRunCreate) SetStartedAt(v time.Time) *AuditRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *AuditRunCreate) SetNillableStartedAt(v *time.Time) *AuditRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *AuditRunCreate) SetCompletedAt(v time.Time) *AuditRunCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *AuditRunCreate) SetNillableCompletedAt(v *time.Time) *AuditRunCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditRunCreate) SetCreatedAt(v time.Time) *AuditRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditRunCreate) SetNillableCreatedAt(v *time.Time) *AuditRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuditRunCreate) SetUpdatedAt(v time.Time) *AuditRunCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuditRunCreate) SetNillableUpdatedAt(v *time.Time) *AuditRunCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAudit sets the "audit" edge to the Audit entity.
func (_c *AuditRunCreate) SetAudit(v *Audit) *AuditRunCreate {
	return _c.SetAuditID(v.ID)
}

// AddIssueIDs adds the "issues" edge to the Issue entity by IDs.
func (_c *AuditRunCreate) AddIssueIDs(ids ...int) *AuditRunCreate {
	_c.mutation.AddIssueIDs(ids...)
	return _c
}

// AddIssues adds the "issues" edges to the Issue entity.
func (_c *AuditRunCreate) AddIssues(v ...*Issue) *AuditRunCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIssueIDs(ids...)
}

// Mutation returns the AuditRunMutation object of the builder.
func (_c *AuditRunCreate) Mutation() *AuditRunMutation {
	return _c.mutation
}

// Save creates the AuditRun in the database.
func (_c *AuditRunCreate) Save(ctx context.Context) (*AuditRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditRunCreate) SaveX(ctx context.Context) *AuditRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditRunCreate) defaults() {
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := auditrun.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := auditrun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := auditrun.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditRunCreate) check() error {
	if _, ok := _c.mutation.AuditID(); !ok {
		return &ValidationError{Name: "audit_id", err: errors.New(`ent: missing required field "AuditRun.audit_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AuditRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := auditrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AuditRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "AuditRun.started_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditRun.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuditRun.updated_at"`)}
	}
	if len(_c.mutation.AuditIDs()) == 0 {
		return &ValidationError{Name: "audit", err: errors.New(`ent: missing required edge "AuditRun.audit"`)}
	}
	return nil
}

func (_c *AuditRunCreate) sqlSave(ctx context.Context) (*AuditRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditRunCreate) createSpec() (*AuditRun, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditrun.Table, sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(auditrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ActualValue(); ok {
		_spec.SetField(auditrun.FieldActualValue, field.TypeString, value)
		_node.ActualValue = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(auditrun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(auditrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(auditrun.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditrun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(auditrun.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AuditIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditrun.AuditTable,
			Columns: []string{auditrun.AuditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuditID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   auditrun.IssuesTable,
			Columns: []string{auditrun.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuditRunCreateBulk is the builder for creating many AuditRun entities in bulk.
type AuditRunCreateBulk struct {
	config
	err      error
	builders []*AuditRunCreate
}

// Save creates the AuditRun entities in the database.
func (_c *AuditRunCreateBulk) Save(ctx context.Context) ([]*AuditRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditRunCreateBulk) SaveX(ctx context.Context) []*AuditRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
