// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"security-central/ent/migrate"

	"security-central/ent/audit"
	"security-central/ent/auditrun"
	"security-central/ent/issue"
	"security-central/ent/policyaudit"
	"security-central/ent/policyrun"
	"security-central/ent/user"
	"security-central/ent/vminventory"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Audit is the client for interacting with the Audit builders.
	Audit *AuditClient
	// AuditRun is the client for interacting with the AuditRun builders.
	AuditRun *AuditRunClient
	// Issue is the client for interacting with the Issue builders.
	Issue *IssueClient
	// PolicyAudit is the client for interacting with the PolicyAudit builders.
	PolicyAudit *PolicyAuditClient
	// PolicyRun is the client for interacting with the PolicyRun builders.
	PolicyRun *PolicyRunClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// VMInventory is the client for interacting with the VMInventory builders.
	VMInventory *VMInventoryClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Audit = NewAuditClient(c.config)
	c.AuditRun = NewAuditRunClient(c.config)
	c.Issue = NewIssueClient(c.config)
	c.PolicyAudit = NewPolicyAuditClient(c.config)
	c.PolicyRun = NewPolicyRunClient(c.config)
	c.User = NewUserClient(c.config)
	c.VMInventory = NewVMInventoryClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Audit:       NewAuditClient(cfg),
		AuditRun:    NewAuditRunClient(cfg),
		Issue:       NewIssueClient(cfg),
		PolicyAudit: NewPolicyAuditClient(cfg),
		PolicyRun:   NewPolicyRunClient(cfg),
		User:        NewUserClient(cfg),
		VMInventory: NewVMInventoryClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Audit:       NewAuditClient(cfg),
		AuditRun:    NewAuditRunClient(cfg),
		Issue:       NewIssueClient(cfg),
		PolicyAudit: NewPolicyAuditClient(cfg),
		PolicyRun:   NewPolicyRunClient(cfg),
		User:        NewUserClient(cfg),
		VMInventory: NewVMInventoryClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Audit.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Audit, c.AuditRun, c.Issue, c.PolicyAudit, c.PolicyRun, c.User, c.VMInventory,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Audit, c.AuditRun, c.Issue, c.PolicyAudit, c.PolicyRun, c.User, c.VMInventory,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AuditMutation:
		return c.Audit.mutate(ctx, m)
	case *AuditRunMutation:
		return c.AuditRun.mutate(ctx, m)
	case *IssueMutation:
		return c.Issue.mutate(ctx, m)
	case *PolicyAuditMutation:
		return c.PolicyAudit.mutate(ctx, m)
	case *PolicyRunMutation:
		return c.PolicyRun.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *VMInventoryMutation:
		return c.VMInventory.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AuditClient is a client for the Audit schema.
type AuditClient struct {
	config
}

// NewAuditClient returns a client for the Audit from the given config.
func NewAuditClient(c config) *AuditClient {
	return &AuditClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `audit.Hooks(f(g(h())))`.
func (c *AuditClient) Use(hooks ...Hook) {
	c.hooks.Audit = append(c.hooks.Audit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `audit.Intercept(f(g(h())))`.
func (c *AuditClient) Intercept(interceptors ...Interceptor) {
	c.inters.Audit = append(c.inters.Audit, interceptors...)
}

// Create returns a builder for creating a Audit entity.
func (c *AuditClient) Create() *AuditCreate {
	mutation := newAuditMutation(c.config, OpCreate)
	return &AuditCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Audit entities.
func (c *AuditClient) CreateBulk(builders ...*AuditCreate) *AuditCreateBulk {
	return &AuditCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditClient) MapCreateBulk(slice any, setFunc func(*AuditCreate, int)) *AuditCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditCreateBulk{err: fmt.Errorf("calling to AuditClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Audit.
func (c *AuditClient) Update() *AuditUpdate {
	mutation := newAuditMutation(c.config, OpUpdate)
	return &AuditUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditClient) UpdateOne(_m *Audit) *AuditUpdateOne {
	mutation := newAuditMutation(c.config, OpUpdateOne, withAudit(_m))
	return &AuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditClient) UpdateOneID(id int) *AuditUpdateOne {
	mutation := newAuditMutation(c.config, OpUpdateOne, withAuditID(id))
	return &AuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Audit.
func (c *AuditClient) Delete() *AuditDelete {
	mutation := newAuditMutation(c.config, OpDelete)
	return &AuditDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditClient) DeleteOne(_m *Audit) *AuditDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditClient) DeleteOneID(id int) *AuditDeleteOne {
	builder := c.Delete().Where(audit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditDeleteOne{builder}
}

// Query returns a query builder for Audit.
func (c *AuditClient) Query() *AuditQuery {
	return &AuditQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAudit},
		inters: c.Interceptors(),
	}
}

// Get returns a Audit entity by its id.
func (c *AuditClient) Get(ctx context.Context, id int) (*Audit, error) {
	return c.Query().Where(audit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditClient) GetX(ctx context.Context, id int) *Audit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRuns queries the runs edge of a Audit.
func (c *AuditClient) QueryRuns(_m *Audit) *AuditRunQuery {
	query := (&AuditRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(audit.Table, audit.FieldID, id),
			sqlgraph.To(auditrun.Table, auditrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, audit.RunsTable, audit.RunsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryIssues queries the issues edge of a Audit.
func (c *AuditClient) QueryIssues(_m *Audit) *IssueQuery {
	query := (&IssueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(audit.Table, audit.FieldID, id),
			sqlgraph.To(issue.Table, issue.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, audit.IssuesTable, audit.IssuesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AuditClient) Hooks() []Hook {
	return c.hooks.Audit
}

// Interceptors returns the client interceptors.
func (c *AuditClient) Interceptors() []Interceptor {
	return c.inters.Audit
}

func (c *AuditClient) mutate(ctx context.Context, m *AuditMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Audit mutation op: %q", m.Op())
	}
}

// AuditRunClient is a client for the AuditRun schema.
type AuditRunClient struct {
	config
}

// NewAuditRunClient returns a client for the AuditRun from the given config.
func NewAuditRunClient(c config) *AuditRunClient {
	return &AuditRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditrun.Hooks(f(g(h())))`.
func (c *AuditRunClient) Use(hooks ...Hook) {
	c.hooks.AuditRun = append(c.hooks.AuditRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditrun.Intercept(f(g(h())))`.
func (c *AuditRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditRun = append(c.inters.AuditRun, interceptors...)
}

// Create returns a builder for creating a AuditRun entity.
func (c *AuditRunClient) Create() *AuditRunCreate {
	mutation := newAuditRunMutation(c.config, OpCreate)
	return &AuditRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditRun entities.
func (c *AuditRunClient) CreateBulk(builders ...*AuditRunCreate) *AuditRunCreateBulk {
	return &AuditRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditRunClient) MapCreateBulk(slice any, setFunc func(*AuditRunCreate, int)) *AuditRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditRunCreateBulk{err: fmt.Errorf("calling to AuditRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditRun.
func (c *AuditRunClient) Update() *AuditRunUpdate {
	mutation := newAuditRunMutation(c.config, OpUpdate)
	return &AuditRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditRunClient) UpdateOne(_m *AuditRun) *AuditRunUpdateOne {
	mutation := newAuditRunMutation(c.config, OpUpdateOne, withAuditRun(_m))
	return &AuditRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditRunClient) UpdateOneID(id int) *AuditRunUpdateOne {
	mutation := newAuditRunMutation(c.config, OpUpdateOne, withAuditRunID(id))
	return &AuditRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditRun.
func (c *AuditRunClient) Delete() *AuditRunDelete {
	mutation := newAuditRunMutation(c.config, OpDelete)
	return &AuditRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditRunClient) DeleteOne(_m *AuditRun) *AuditRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditRunClient) DeleteOneID(id int) *AuditRunDeleteOne {
	builder := c.Delete().Where(auditrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditRunDeleteOne{builder}
}

// Query returns a query builder for AuditRun.
func (c *AuditRunClient) Query() *AuditRunQuery {
	return &AuditRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditRun},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditRun entity by its id.
func (c *AuditRunClient) Get(ctx context.Context, id int) (*AuditRun, error) {
	return c.Query().Where(auditrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditRunClient) GetX(ctx context.Context, id int) *AuditRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAudit queries the audit edge of a AuditRun.
func (c *AuditRunClient) QueryAudit(_m *AuditRun) *AuditQuery {
	query := (&AuditClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(auditrun.Table, auditrun.FieldID, id),
			sqlgraph.To(audit.Table, audit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, auditrun.AuditTable, auditrun.AuditColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryIssues queries the issues edge of a AuditRun.
func (c *AuditRunClient) QueryIssues(_m *AuditRun) *IssueQuery {
	query := (&IssueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(auditrun.Table, auditrun.FieldID, id),
			sqlgraph.To(issue.Table, issue.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, auditrun.IssuesTable, auditrun.IssuesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AuditRunClient) Hooks() []Hook {
	return c.hooks.AuditRun
}

// Interceptors returns the client interceptors.
func (c *AuditRunClient) Interceptors() []Interceptor {
	return c.inters.AuditRun
}

func (c *AuditRunClient) mutate(ctx context.Context, m *AuditRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditRun mutation op: %q", m.Op())
	}
}

// IssueClient is a client for the Issue schema.
type IssueClient struct {
	config
}

// NewIssueClient returns a client for the Issue from the given config.
func NewIssueClient(c config) *IssueClient {
	return &IssueClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `issue.Hooks(f(g(h())))`.
func (c *IssueClient) Use(hooks ...Hook) {
	c.hooks.Issue = append(c.hooks.Issue, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `issue.Intercept(f(g(h())))`.
func (c *IssueClient) Intercept(interceptors ...Interceptor) {
	c.inters.Issue = append(c.inters.Issue, interceptors...)
}

// Create returns a builder for creating a Issue entity.
func (c *IssueClient) Create() *IssueCreate {
	mutation := newIssueMutation(c.config, OpCreate)
	return &IssueCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Issue entities.
func (c *IssueClient) CreateBulk(builders ...*IssueCreate) *IssueCreateBulk {
	return &IssueCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IssueClient) MapCreateBulk(slice any, setFunc func(*IssueCreate, int)) *IssueCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IssueCreateBulk{err: fmt.Errorf("calling to IssueClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IssueCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IssueCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Issue.
func (c *IssueClient) Update() *IssueUpdate {
	mutation := newIssueMutation(c.config, OpUpdate)
	return &IssueUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IssueClient) UpdateOne(_m *Issue) *IssueUpdateOne {
	mutation := newIssueMutation(c.config, OpUpdateOne, withIssue(_m))
	return &IssueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IssueClient) UpdateOneID(id int) *IssueUpdateOne {
	mutation := newIssueMutation(c.config, OpUpdateOne, withIssueID(id))
	return &IssueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Issue.
func (c *IssueClient) Delete() *IssueDelete {
	mutation := newIssueMutation(c.config, OpDelete)
	return &IssueDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IssueClient) DeleteOne(_m *Issue) *IssueDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IssueClient) DeleteOneID(id int) *IssueDeleteOne {
	builder := c.Delete().Where(issue.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IssueDeleteOne{builder}
}

// Query returns a query builder for Issue.
func (c *IssueClient) Query() *IssueQuery {
	return &IssueQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIssue},
		inters: c.Interceptors(),
	}
}

// Get returns a Issue entity by its id.
func (c *IssueClient) Get(ctx context.Context, id int) (*Issue, error) {
	return c.Query().Where(issue.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IssueClient) GetX(ctx context.Context, id int) *Issue {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAudit queries the audit edge of a Issue.
func (c *IssueClient) QueryAudit(_m *Issue) *AuditQuery {
	query := (&AuditClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(issue.Table, issue.FieldID, id),
			sqlgraph.To(audit.Table, audit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, issue.AuditTable, issue.AuditColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAuditRun queries the audit_run edge of a Issue.
func (c *IssueClient) QueryAuditRun(_m *Issue) *AuditRunQuery {
	query := (&AuditRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(issue.Table, issue.FieldID, id),
			sqlgraph.To(auditrun.Table, auditrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, issue.AuditRunTable, issue.AuditRunColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IssueClient) Hooks() []Hook {
	return c.hooks.Issue
}

// Interceptors returns the client interceptors.
func (c *IssueClient) Interceptors() []Interceptor {
	return c.inters.Issue
}

func (c *IssueClient) mutate(ctx context.Context, m *IssueMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IssueCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IssueUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IssueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IssueDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Issue mutation op: %q", m.Op())
	}
}

// PolicyAuditClient is a client for the PolicyAudit schema.
type PolicyAuditClient struct {
	config
}

// NewPolicyAuditClient returns a client for the PolicyAudit from the given config.
func NewPolicyAuditClient(c config) *PolicyAuditClient {
	return &PolicyAuditClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `policyaudit.Hooks(f(g(h())))`.
func (c *PolicyAuditClient) Use(hooks ...Hook) {
	c.hooks.PolicyAudit = append(c.hooks.PolicyAudit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `policyaudit.Intercept(f(g(h())))`.
func (c *PolicyAuditClient) Intercept(interceptors ...Interceptor) {
	c.inters.PolicyAudit = append(c.inters.PolicyAudit, interceptors...)
}

// Create returns a builder for creating a PolicyAudit entity.
func (c *PolicyAuditClient) Create() *PolicyAuditCreate {
	mutation := newPolicyAuditMutation(c.config, OpCreate)
	return &PolicyAuditCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PolicyAudit entities.
func (c *PolicyAuditClient) CreateBulk(builders ...*PolicyAuditCreate) *PolicyAuditCreateBulk {
	return &PolicyAuditCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PolicyAuditClient) MapCreateBulk(slice any, setFunc func(*PolicyAuditCreate, int)) *PolicyAuditCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PolicyAuditCreateBulk{err: fmt.Errorf("calling to PolicyAuditClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PolicyAuditCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PolicyAuditCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PolicyAudit.
func (c *PolicyAuditClient) Update() *PolicyAuditUpdate {
	mutation := newPolicyAuditMutation(c.config, OpUpdate)
	return &PolicyAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PolicyAuditClient) UpdateOne(_m *PolicyAudit) *PolicyAuditUpdateOne {
	mutation := newPolicyAuditMutation(c.config, OpUpdateOne, withPolicyAudit(_m))
	return &PolicyAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PolicyAuditClient) UpdateOneID(id int) *PolicyAuditUpdateOne {
	mutation := newPolicyAuditMutation(c.config, OpUpdateOne, withPolicyAuditID(id))
	return &PolicyAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PolicyAudit.
func (c *PolicyAuditClient) Delete() *PolicyAuditDelete {
	mutation := newPolicyAuditMutation(c.config, OpDelete)
	return &PolicyAuditDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PolicyAuditClient) DeleteOne(_m *PolicyAudit) *PolicyAuditDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PolicyAuditClient) DeleteOneID(id int) *PolicyAuditDeleteOne {
	builder := c.Delete().Where(policyaudit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PolicyAuditDeleteOne{builder}
}

// Query returns a query builder for PolicyAudit.
func (c *PolicyAuditClient) Query() *PolicyAuditQuery {
	return &PolicyAuditQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePolicyAudit},
		inters: c.Interceptors(),
	}
}

// Get returns a PolicyAudit entity by its id.
func (c *PolicyAuditClient) Get(ctx context.Context, id int) (*PolicyAudit, error) {
	return c.Query().Where(policyaudit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PolicyAuditClient) GetX(ctx context.Context, id int) *PolicyAudit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PolicyAuditClient) Hooks() []Hook {
	return c.hooks.PolicyAudit
}

// Interceptors returns the client interceptors.
func (c *PolicyAuditClient) Interceptors() []Interceptor {
	return c.inters.PolicyAudit
}

func (c *PolicyAuditClient) mutate(ctx context.Context, m *PolicyAuditMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PolicyAuditCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PolicyAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PolicyAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PolicyAuditDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PolicyAudit mutation op: %q", m.Op())
	}
}

// PolicyRunClient is a client for the PolicyRun schema.
type PolicyRunClient struct {
	config
}

// NewPolicyRunClient returns a client for the PolicyRun from the given config.
func NewPolicyRunClient(c config) *PolicyRunClient {
	return &PolicyRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `policyrun.Hooks(f(g(h())))`.
func (c *PolicyRunClient) Use(hooks ...Hook) {
	c.hooks.PolicyRun = append(c.hooks.PolicyRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `policyrun.Intercept(f(g(h())))`.
func (c *PolicyRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.PolicyRun = append(c.inters.PolicyRun, interceptors...)
}

// Create returns a builder for creating a PolicyRun entity.
func (c *PolicyRunClient) Create() *PolicyRunCreate {
	mutation := newPolicyRunMutation(c.config, OpCreate)
	return &PolicyRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PolicyRun entities.
func (c *PolicyRunClient) CreateBulk(builders ...*PolicyRunCreate) *PolicyRunCreateBulk {
	return &PolicyRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PolicyRunClient) MapCreateBulk(slice any, setFunc func(*PolicyRunCreate, int)) *PolicyRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PolicyRunCreateBulk{err: fmt.Errorf("calling to PolicyRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PolicyRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PolicyRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PolicyRun.
func (c *PolicyRunClient) Update() *PolicyRunUpdate {
	mutation := newPolicyRunMutation(c.config, OpUpdate)
	return &PolicyRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PolicyRunClient) UpdateOne(_m *PolicyRun) *PolicyRunUpdateOne {
	mutation := newPolicyRunMutation(c.config, OpUpdateOne, withPolicyRun(_m))
	return &PolicyRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PolicyRunClient) UpdateOneID(id int) *PolicyRunUpdateOne {
	mutation := newPolicyRunMutation(c.config, OpUpdateOne, withPolicyRunID(id))
	return &PolicyRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PolicyRun.
func (c *PolicyRunClient) Delete() *PolicyRunDelete {
	mutation := newPolicyRunMutation(c.config, OpDelete)
	return &PolicyRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PolicyRunClient) DeleteOne(_m *PolicyRun) *PolicyRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PolicyRunClient) DeleteOneID(id int) *PolicyRunDeleteOne {
	builder := c.Delete().Where(policyrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PolicyRunDeleteOne{builder}
}

// Query returns a query builder for PolicyRun.
func (c *PolicyRunClient) Query() *PolicyRunQuery {
	return &PolicyRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePolicyRun},
		inters: c.Interceptors(),
	}
}

// Get returns a PolicyRun entity by its id.
func (c *PolicyRunClient) Get(ctx context.Context, id int) (*PolicyRun, error) {
	return c.Query().Where(policyrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PolicyRunClient) GetX(ctx context.Context, id int) *PolicyRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PolicyRunClient) Hooks() []Hook {
	return c.hooks.PolicyRun
}

// Interceptors returns the client interceptors.
func (c *PolicyRunClient) Interceptors() []Interceptor {
	return c.inters.PolicyRun
}

func (c *PolicyRunClient) mutate(ctx context.Context, m *PolicyRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PolicyRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PolicyRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PolicyRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PolicyRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PolicyRun mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// VMInventoryClient is a client for the VMInventory schema.
type VMInventoryClient struct {
	config
}

// NewVMInventoryClient returns a client for the VMInventory from the given config.
func NewVMInventoryClient(c config) *VMInventoryClient {
	return &VMInventoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `vminventory.Hooks(f(g(h())))`.
func (c *VMInventoryClient) Use(hooks ...Hook) {
	c.hooks.VMInventory = append(c.hooks.VMInventory, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `vminventory.Intercept(f(g(h())))`.
func (c *VMInventoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.VMInventory = append(c.inters.VMInventory, interceptors...)
}

// Create returns a builder for creating a VMInventory entity.
func (c *VMInventoryClient) Create() *VMInventoryCreate {
	mutation := newVMInventoryMutation(c.config, OpCreate)
	return &VMInventoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VMInventory entities.
func (c *VMInventoryClient) CreateBulk(builders ...*VMInventoryCreate) *VMInventoryCreateBulk {
	return &VMInventoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *VMInventoryClient) MapCreateBulk(slice any, setFunc func(*VMInventoryCreate, int)) *VMInventoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &VMInventoryCreateBulk{err: fmt.Errorf("calling to VMInventoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*VMInventoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &VMInventoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VMInventory.
func (c *VMInventoryClient) Update() *VMInventoryUpdate {
	mutation := newVMInventoryMutation(c.config, OpUpdate)
	return &VMInventoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VMInventoryClient) UpdateOne(_m *VMInventory) *VMInventoryUpdateOne {
	mutation := newVMInventoryMutation(c.config, OpUpdateOne, withVMInventory(_m))
	return &VMInventoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VMInventoryClient) UpdateOneID(id int) *VMInventoryUpdateOne {
	mutation := newVMInventoryMutation(c.config, OpUpdateOne, withVMInventoryID(id))
	return &VMInventoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VMInventory.
func (c *VMInventoryClient) Delete() *VMInventoryDelete {
	mutation := newVMInventoryMutation(c.config, OpDelete)
	return &VMInventoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *VMInventoryClient) DeleteOne(_m *VMInventory) *VMInventoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *VMInventoryClient) DeleteOneID(id int) *VMInventoryDeleteOne {
	builder := c.Delete().Where(vminventory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VMInventoryDeleteOne{builder}
}

// Query returns a query builder for VMInventory.
func (c *VMInventoryClient) Query() *VMInventoryQuery {
	return &VMInventoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeVMInventory},
		inters: c.Interceptors(),
	}
}

// Get returns a VMInventory entity by its id.
func (c *VMInventoryClient) Get(ctx context.Context, id int) (*VMInventory, error) {
	return c.Query().Where(vminventory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VMInventoryClient) GetX(ctx context.Context, id int) *VMInventory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *VMInventoryClient) Hooks() []Hook {
	return c.hooks.VMInventory
}

// Interceptors returns the client interceptors.
func (c *VMInventoryClient) Interceptors() []Interceptor {
	return c.inters.VMInventory
}

func (c *VMInventoryClient) mutate(ctx context.Context, m *VMInventoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&VMInventoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&VMInventoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&VMInventoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&VMInventoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown VMInventory mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Audit, AuditRun, Issue, PolicyAudit, PolicyRun, User, VMInventory []ent.Hook
	}
	inters struct {
		Audit, AuditRun, Issue, PolicyAudit, PolicyRun, User,
		VMInventory []ent.Interceptor
	}
)
