// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/audit"
	"security-central/ent/auditrun"
	"security-central/ent/issue"
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IssueUpdate is the builder for updating Issue entities.
type IssueUpdate struct {
	config
	hooks    []Hook
	mutation *IssueMutation
}

// Where appends a list predicates to the IssueUpdate builder.
func (_u *IssueUpdate) Where(ps ...predicate.Issue) *IssueUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAuditID sets the "audit_id" field.
func (_u *IssueUpdate) SetAuditID(v int) *IssueUpdate {
	_u.mutation.SetAuditID(v)
	return _u
}

// SetNillableAuditID sets the "audit_id" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableAuditID(v *int) *IssueUpdate {
	if v != nil {
		_u.SetAuditID(*v)
	}
	return _u
}

// SetAuditRunID sets the "audit_run_id" field.
func (_u *IssueUpdate) SetAuditRunID(v int) *IssueUpdate {
	_u.mutation.SetAuditRunID(v)
	return _u
}

// SetNillableAuditRunID sets the "audit_run_id" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableAuditRunID(v *int) *IssueUpdate {
	if v != nil {
		_u.SetAuditRunID(*v)
	}
	return _u
}

// SetExpectedValue sets the "expected_value" field.
func (_u *IssueUpdate) SetExpectedValue(v string) *IssueUpdate {
	_u.mutation.SetExpectedValue(v)
	return _u
}

// SetNillableExpectedValue sets the "expected_value" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableExpectedValue(v *string) *IssueUpdate {
	if v != nil {
		_u.SetExpectedValue(*v)
	}
	return _u
}

// SetActualValue sets the "actual_value" field.
func (_u *IssueUpdate) SetActualValue(v string) *IssueUpdate {
	_u.mutation.SetActualValue(v)
	return _u
}

// SetNillableActualValue sets the "actual_value" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableActualValue(v *string) *IssueUpdate {
	if v != nil {
		_u.SetActualValue(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *IssueUpdate) SetDescription(v string) *IssueUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableDescription(v *string) *IssueUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IssueUpdate) SetCreatedAt(v time.Time) *IssueUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableCreatedAt(v *time.Time) *IssueUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IssueUpdate) SetUpdatedAt(v time.Time) *IssueUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAudit sets the "audit" edge to the Audit entity.
func (_u *IssueUpdate) SetAudit(v *Audit) *IssueUpdate {
	return _u.SetAuditID(v.ID)
}

// SetAuditRun sets the "audit_run" edge to the AuditRun entity.
func (_u *IssueUpdate) SetAuditRun(v *AuditRun) *IssueUpdate {
	return _u.SetAuditRunID(v.ID)
}

// Mutation returns the IssueMutation object of the builder.
func (_u *IssueUpdate) Mutation() *IssueMutation {
	return _u.mutation
}

// ClearAudit clears the "audit" edge to the Audit entity.
func (_u *IssueUpdate) ClearAudit() *IssueUpdate {
	_u.mutation.ClearAudit()
	return _u
}

// ClearAuditRun clears the "audit_run" edge to the AuditRun entity.
func (_u *IssueUpdate) ClearAuditRun() *IssueUpdate {
	_u.mutation.ClearAuditRun()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IssueUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IssueUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IssueUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IssueUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IssueUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := issue.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IssueUpdate) check() error {
	if v, ok := _u.mutation.ExpectedValue(); ok {
		if err := issue.ExpectedValueValidator(v); err != nil {
			return &ValidationError{Name: "expected_value", err: fmt.Errorf(`ent: validator failed for field "Issue.expected_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualValue(); ok {
		if err := issue.ActualValueValidator(v); err != nil {
			return &ValidationError{Name: "actual_value", err: fmt.Errorf(`ent: validator failed for field "Issue.actual_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := issue.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Issue.description": %w`, err)}
		}
	}
	if _u.mutation.AuditCleared() && len(_u.mutation.AuditIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Issue.audit"`)
	}
	if _u.mutation.AuditRunCleared() && len(_u.mutation.AuditRunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Issue.audit_run"`)
	}
	return nil
}

func (_u *IssueUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(issue.Table, issue.Columns, sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExpectedValue(); ok {
		_spec.SetField(issue.FieldExpectedValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualValue(); ok {
		_spec.SetField(issue.FieldActualValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(issue.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(issue.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(issue.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AuditCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.AuditTable,
			Columns: []string{issue.AuditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.AuditTable,
			Columns: []string{issue.AuditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.AuditRunTable,
			Columns: []string{issue.AuditRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.AuditRunTable,
			Columns: []string{issue.AuditRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IssueUpdateOne is the builder for updating a single Issue entity.
type IssueUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IssueMutation
}

// SetAuditID sets the "audit_id" field.
func (_u *IssueUpdateOne) SetAuditID(v int) *IssueUpdateOne {
	_u.mutation.SetAuditID(v)
	return _u
}

// SetNillableAuditID sets the "audit_id" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableAuditID(v *int) *IssueUpdateOne {
	if v != nil {
		_u.SetAuditID(*v)
	}
	return _u
}

// SetAuditRunID sets the "audit_run_id" field.
func (_u *IssueUpdateOne) SetAuditRunID(v int) *IssueUpdateOne {
	_u.mutation.SetAuditRunID(v)
	return _u
}

// SetNillableAuditRunID sets the "audit_run_id" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableAuditRunID(v *int) *IssueUpdateOne {
	if v != nil {
		_u.SetAuditRunID(*v)
	}
	return _u
}

// SetExpectedValue sets the "expected_value" field.
func (_u *IssueUpdateOne) SetExpectedValue(v string) *IssueUpdateOne {
	_u.mutation.SetExpectedValue(v)
	return _u
}

// SetNillableExpectedValue sets the "expected_value" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableExpectedValue(v *string) *IssueUpdateOne {
	if v != nil {
		_u.SetExpectedValue(*v)
	}
	return _u
}

// SetActualValue sets the "actual_value" field.
func (_u *IssueUpdateOne) SetActualValue(v string) *IssueUpdateOne {
	_u.mutation.SetActualValue(v)
	return _u
}

// SetNillableActualValue sets the "actual_value" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableActualValue(v *string) *IssueUpdateOne {
	if v != nil {
		_u.SetActualValue(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *IssueUpdateOne) SetDescription(v string) *IssueUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableDescription(v *string) *IssueUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IssueUpdateOne) SetCreatedAt(v time.Time) *IssueUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableCreatedAt(v *time.Time) *IssueUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IssueUpdateOne) SetUpdatedAt(v time.Time) *IssueUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAudit sets the "audit" edge to the Audit entity.
func (_u *IssueUpdateOne) SetAudit(v *Audit) *IssueUpdateOne {
	return _u.SetAuditID(v.ID)
}

// SetAuditRun sets the "audit_run" edge to the AuditRun entity.
func (_u *IssueUpdateOne) SetAuditRun(v *AuditRun) *IssueUpdateOne {
	return _u.SetAuditRunID(v.ID)
}

// Mutation returns the IssueMutation object of the builder.
func (_u *IssueUpdateOne) Mutation() *IssueMutation {
	return _u.mutation
}

// ClearAudit clears the "audit" edge to the Audit entity.
func (_u *IssueUpdateOne) ClearAudit() *IssueUpdateOne {
	_u.mutation.ClearAudit()
	return _u
}

// ClearAuditRun clears the "audit_run" edge to the AuditRun entity.
func (_u *IssueUpdateOne) ClearAuditRun() *IssueUpdateOne {
	_u.mutation.ClearAuditRun()
	return _u
}

// Where appends a list predicates to the IssueUpdate builder.
func (_u *IssueUpdateOne) Where(ps ...predicate.Issue) *IssueUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IssueUpdateOne) Select(field string, fields ...string) *IssueUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Issue entity.
func (_u *IssueUpdateOne) Save(ctx context.Context) (*Issue, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IssueUpdateOne) SaveX(ctx context.Context) *Issue {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IssueUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IssueUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IssueUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := issue.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IssueUpdateOne) check() error {
	if v, ok := _u.mutation.ExpectedValue(); ok {
		if err := issue.ExpectedValueValidator(v); err != nil {
			return &ValidationError{Name: "expected_value", err: fmt.Errorf(`ent: validator failed for field "Issue.expected_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualValue(); ok {
		if err := issue.ActualValueValidator(v); err != nil {
			return &ValidationError{Name: "actual_value", err: fmt.Errorf(`ent: validator failed for field "Issue.actual_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := issue.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Issue.description": %w`, err)}
		}
	}
	if _u.mutation.AuditCleared() && len(_u.mutation.AuditIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Issue.audit"`)
	}
	if _u.mutation.AuditRunCleared() && len(_u.mutation.AuditRunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Issue.audit_run"`)
	}
	return nil
}

func (_u *IssueUpdateOne) sqlSave(ctx context.Context) (_node *Issue, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(issue.Table, issue.Columns, sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Issue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issue.FieldID)
		for _, f := range fields {
			if !issue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != issue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExpectedValue(); ok {
		_spec.SetField(issue.FieldExpectedValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActualValue(); ok {
		_spec.SetField(issue.FieldActualValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(issue.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(issue.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(issue.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AuditCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.AuditTable,
			Columns: []string{issue.AuditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.AuditTable,
			Columns: []string{issue.AuditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(audit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuditRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.AuditRunTable,
			Columns: []string{issue.AuditRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.AuditRunTable,
			Columns: []string{issue.AuditRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Issue{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
