// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"security-central/ent/audit"
	"security-central/ent/auditrun"
	"security-central/ent/issue"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Issue is the model entity for the Issue schema.
type Issue struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AuditID holds the value of the "audit_id" field.
	AuditID int `json:"audit_id,omitempty"`
	// AuditRunID holds the value of the "audit_run_id" field.
	AuditRunID int `json:"audit_run_id,omitempty"`
	// QueryName holds the value of the "query_name" field.
	QueryName string `json:"query_name,omitempty"`
	// ExpectedValue holds the value of the "expected_value" field.
	ExpectedValue string `json:"expected_value,omitempty"`
	// ActualValue holds the value of the "actual_value" field.
	ActualValue string `json:"actual_value,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IssueQuery when eager-loading is set.
	Edges        IssueEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IssueEdges holds the relations/edges for other nodes in the graph.
type IssueEdges struct {
	// Audit holds the value of the audit edge.
	Audit *Audit `json:"audit,omitempty"`
	// AuditRun holds the value of the audit_run edge.
	AuditRun *AuditRun `json:"audit_run,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AuditOrErr returns the Audit value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IssueEdges) AuditOrErr() (*Audit, error) {
	if e.Audit != nil {
		return e.Audit, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: audit.Label}
	}
	return nil, &NotLoadedError{edge: "audit"}
}

// AuditRunOrErr returns the AuditRun value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IssueEdges) AuditRunOrErr() (*AuditRun, error) {
	if e.AuditRun != nil {
		return e.AuditRun, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: auditrun.Label}
	}
	return nil, &NotLoadedError{edge: "audit_run"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Issue) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case issue.FieldID, issue.FieldAuditID, issue.FieldAuditRunID:
			values[i] = new(sql.NullInt64)
		case issue.FieldQueryName, issue.FieldExpectedValue, issue.FieldActualValue, issue.FieldDescription:
			values[i] = new(sql.NullString)
		case issue.FieldCreatedAt, issue.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Issue fields.
func (_m *Issue) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case issue.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case issue.FieldAuditID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field audit_id", values[i])
			} else if value.Valid {
				_m.AuditID = int(value.Int64)
			}
		case issue.FieldAuditRunID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field audit_run_id", values[i])
			} else if value.Valid {
				_m.AuditRunID = int(value.Int64)
			}
		case issue.FieldQueryName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query_name", values[i])
			} else if value.Valid {
				_m.QueryName = value.String
			}
		case issue.FieldExpectedValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field expected_value", values[i])
			} else if value.Valid {
				_m.ExpectedValue = value.String
			}
		case issue.FieldActualValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actual_value", values[i])
			} else if value.Valid {
				_m.ActualValue = value.String
			}
		case issue.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case issue.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case issue.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Issue.
// This includes values selected through modifiers, order, etc.
func (_m *Issue) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAudit queries the "audit" edge of the Issue entity.
func (_m *Issue) QueryAudit() *AuditQuery {
	return NewIssueClient(_m.config).QueryAudit(_m)
}

// QueryAuditRun queries the "audit_run" edge of the Issue entity.
func (_m *Issue) QueryAuditRun() *AuditRunQuery {
	return NewIssueClient(_m.config).QueryAuditRun(_m)
}

// Update returns a builder for updating this Issue.
// Note that you need to call Issue.Unwrap() before calling this method if this Issue
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Issue) Update() *IssueUpdateOne {
	return NewIssueClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Issue entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Issue) Unwrap() *Issue {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Issue is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Issue) String() string {
	var builder strings.Builder
	builder.WriteString("Issue(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("audit_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuditID))
	builder.WriteString(", ")
	builder.WriteString("audit_run_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuditRunID))
	builder.WriteString(", ")
	builder.WriteString("query_name=")
	builder.WriteString(_m.QueryName)
	builder.WriteString(", ")
	builder.WriteString("expected_value=")
	builder.WriteString(_m.ExpectedValue)
	builder.WriteString(", ")
	builder.WriteString("actual_value=")
	builder.WriteString(_m.ActualValue)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Issues is a parsable slice of Issue.
type Issues []*Issue
