// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/audit"
	"security-central/ent/auditrun"
	"security-central/ent/issue"
	"security-central/ent/predicate"
	"security-central/ent/vminventory"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAudit       = "Audit"
	TypeAuditRun    = "AuditRun"
	TypeIssue       = "Issue"
	TypeVMInventory = "VMInventory"
)

// AuditMutation represents an operation that mutates the Audit nodes in the graph.
type AuditMutation struct {
	config
	op             Op
	typ            string
	id             *int
	name           *string
	sql_query      *string
	expected_type  *string
	expected_value *string
	created_at     *time.Time
	updated_at     *time.Time
	clearedFields  map[string]struct{}
	runs           map[int]struct{}
	removedruns    map[int]struct{}
	clearedruns    bool
	issues         map[int]struct{}
	removedissues  map[int]struct{}
	clearedissues  bool
	done           bool
	oldValue       func(context.Context) (*Audit, error)
	predicates     []predicate.Audit
}

var _ ent.Mutation = (*AuditMutation)(nil)

// auditOption allows management of the mutation configuration using functional options.
type auditOption func(*AuditMutation)

// newAuditMutation creates new mutation for the Audit entity.
func newAuditMutation(c config, op Op, opts ...auditOption) *AuditMutation {
	m := &AuditMutation{
		config:        c,
		op:            op,
		typ:           TypeAudit,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAuditID sets the ID field of the mutation.
func withAuditID(id int) auditOption {
	return func(m *AuditMutation) {
		var (
			err   error
			once  sync.Once
			value *Audit
		)
		m.oldValue = func(ctx context.Context) (*Audit, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Audit.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAudit sets the old Audit of the mutation.
func withAudit(node *Audit) auditOption {
	return func(m *AuditMutation) {
		m.oldValue = func(context.Context) (*Audit, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AuditMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AuditMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AuditMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AuditMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Audit.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *AuditMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *AuditMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Audit entity.
// If the Audit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *AuditMutation) ResetName() {
	m.name = nil
}

// SetSQLQuery sets the "sql_query" field.
func (m *AuditMutation) SetSQLQuery(s string) {
	m.sql_query = &s
}

// SQLQuery returns the value of the "sql_query" field in the mutation.
func (m *AuditMutation) SQLQuery() (r string, exists bool) {
	v := m.sql_query
	if v == nil {
		return
	}
	return *v, true
}

// OldSQLQuery returns the old "sql_query" field's value of the Audit entity.
// If the Audit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditMutation) OldSQLQuery(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSQLQuery is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSQLQuery requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSQLQuery: %w", err)
	}
	return oldValue.SQLQuery, nil
}

// ResetSQLQuery resets all changes to the "sql_query" field.
func (m *AuditMutation) ResetSQLQuery() {
	m.sql_query = nil
}

// SetExpectedType sets the "expected_type" field.
func (m *AuditMutation) SetExpectedType(s string) {
	m.expected_type = &s
}

// ExpectedType returns the value of the "expected_type" field in the mutation.
func (m *AuditMutation) ExpectedType() (r string, exists bool) {
	v := m.expected_type
	if v == nil {
		return
	}
	return *v, true
}

// OldExpectedType returns the old "expected_type" field's value of the Audit entity.
// If the Audit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditMutation) OldExpectedType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpectedType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpectedType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpectedType: %w", err)
	}
	return oldValue.ExpectedType, nil
}

// ResetExpectedType resets all changes to the "expected_type" field.
func (m *AuditMutation) ResetExpectedType() {
	m.expected_type = nil
}

// SetExpectedValue sets the "expected_value" field.
func (m *AuditMutation) SetExpectedValue(s string) {
	m.expected_value = &s
}

// ExpectedValue returns the value of the "expected_value" field in the mutation.
func (m *AuditMutation) ExpectedValue() (r string, exists bool) {
	v := m.expected_value
	if v == nil {
		return
	}
	return *v, true
}

// OldExpectedValue returns the old "expected_value" field's value of the Audit entity.
// If the Audit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditMutation) OldExpectedValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpectedValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpectedValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpectedValue: %w", err)
	}
	return oldValue.ExpectedValue, nil
}

// ResetExpectedValue resets all changes to the "expected_value" field.
func (m *AuditMutation) ResetExpectedValue() {
	m.expected_value = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *AuditMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AuditMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Audit entity.
// If the Audit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AuditMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AuditMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AuditMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Audit entity.
// If the Audit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AuditMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddRunIDs adds the "runs" edge to the AuditRun entity by ids.
func (m *AuditMutation) AddRunIDs(ids ...int) {
	if m.runs == nil {
		m.runs = make(map[int]struct{})
	}
	for i := range ids {
		m.runs[ids[i]] = struct{}{}
	}
}

// ClearRuns clears the "runs" edge to the AuditRun entity.
func (m *AuditMutation) ClearRuns() {
	m.clearedruns = true
}

// RunsCleared reports if the "runs" edge to the AuditRun entity was cleared.
func (m *AuditMutation) RunsCleared() bool {
	return m.clearedruns
}

// RemoveRunIDs removes the "runs" edge to the AuditRun entity by IDs.
func (m *AuditMutation) RemoveRunIDs(ids ...int) {
	if m.removedruns == nil {
		m.removedruns = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.runs, ids[i])
		m.removedruns[ids[i]] = struct{}{}
	}
}

// RemovedRuns returns the removed IDs of the "runs" edge to the AuditRun entity.
func (m *AuditMutation) RemovedRunsIDs() (ids []int) {
	for id := range m.removedruns {
		ids = append(ids, id)
	}
	return
}

// RunsIDs returns the "runs" edge IDs in the mutation.
func (m *AuditMutation) RunsIDs() (ids []int) {
	for id := range m.runs {
		ids = append(ids, id)
	}
	return
}

// ResetRuns resets all changes to the "runs" edge.
func (m *AuditMutation) ResetRuns() {
	m.runs = nil
	m.clearedruns = false
	m.removedruns = nil
}

// AddIssueIDs adds the "issues" edge to the Issue entity by ids.
func (m *AuditMutation) AddIssueIDs(ids ...int) {
	if m.issues == nil {
		m.issues = make(map[int]struct{})
	}
	for i := range ids {
		m.issues[ids[i]] = struct{}{}
	}
}

// ClearIssues clears the "issues" edge to the Issue entity.
func (m *AuditMutation) ClearIssues() {
	m.clearedissues = true
}

// IssuesCleared reports if the "issues" edge to the Issue entity was cleared.
func (m *AuditMutation) IssuesCleared() bool {
	return m.clearedissues
}

// RemoveIssueIDs removes the "issues" edge to the Issue entity by IDs.
func (m *AuditMutation) RemoveIssueIDs(ids ...int) {
	if m.removedissues == nil {
		m.removedissues = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.issues, ids[i])
		m.removedissues[ids[i]] = struct{}{}
	}
}

// RemovedIssues returns the removed IDs of the "issues" edge to the Issue entity.
func (m *AuditMutation) RemovedIssuesIDs() (ids []int) {
	for id := range m.removedissues {
		ids = append(ids, id)
	}
	return
}

// IssuesIDs returns the "issues" edge IDs in the mutation.
func (m *AuditMutation) IssuesIDs() (ids []int) {
	for id := range m.issues {
		ids = append(ids, id)
	}
	return
}

// ResetIssues resets all changes to the "issues" edge.
func (m *AuditMutation) ResetIssues() {
	m.issues = nil
	m.clearedissues = false
	m.removedissues = nil
}

// Where appends a list predicates to the AuditMutation builder.
func (m *AuditMutation) Where(ps ...predicate.Audit) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AuditMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AuditMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Audit, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AuditMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AuditMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Audit).
func (m *AuditMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AuditMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, audit.FieldName)
	}
	if m.sql_query != nil {
		fields = append(fields, audit.FieldSQLQuery)
	}
	if m.expected_type != nil {
		fields = append(fields, audit.FieldExpectedType)
	}
	if m.expected_value != nil {
		fields = append(fields, audit.FieldExpectedValue)
	}
	if m.created_at != nil {
		fields = append(fields, audit.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, audit.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AuditMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case audit.FieldName:
		return m.Name()
	case audit.FieldSQLQuery:
		return m.SQLQuery()
	case audit.FieldExpectedType:
		return m.ExpectedType()
	case audit.FieldExpectedValue:
		return m.ExpectedValue()
	case audit.FieldCreatedAt:
		return m.CreatedAt()
	case audit.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AuditMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case audit.FieldName:
		return m.OldName(ctx)
	case audit.FieldSQLQuery:
		return m.OldSQLQuery(ctx)
	case audit.FieldExpectedType:
		return m.OldExpectedType(ctx)
	case audit.FieldExpectedValue:
		return m.OldExpectedValue(ctx)
	case audit.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case audit.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Audit field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditMutation) SetField(name string, value ent.Value) error {
	switch name {
	case audit.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case audit.FieldSQLQuery:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSQLQuery(v)
		return nil
	case audit.FieldExpectedType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpectedType(v)
		return nil
	case audit.FieldExpectedValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpectedValue(v)
		return nil
	case audit.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case audit.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Audit field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AuditMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AuditMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Audit numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AuditMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AuditMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AuditMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Audit nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AuditMutation) ResetField(name string) error {
	switch name {
	case audit.FieldName:
		m.ResetName()
		return nil
	case audit.FieldSQLQuery:
		m.ResetSQLQuery()
		return nil
	case audit.FieldExpectedType:
		m.ResetExpectedType()
		return nil
	case audit.FieldExpectedValue:
		m.ResetExpectedValue()
		return nil
	case audit.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case audit.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Audit field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AuditMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.runs != nil {
		edges = append(edges, audit.EdgeRuns)
	}
	if m.issues != nil {
		edges = append(edges, audit.EdgeIssues)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AuditMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case audit.EdgeRuns:
		ids := make([]ent.Value, 0, len(m.runs))
		for id := range m.runs {
			ids = append(ids, id)
		}
		return ids
	case audit.EdgeIssues:
		ids := make([]ent.Value, 0, len(m.issues))
		for id := range m.issues {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AuditMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedruns != nil {
		edges = append(edges, audit.EdgeRuns)
	}
	if m.removedissues != nil {
		edges = append(edges, audit.EdgeIssues)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AuditMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case audit.EdgeRuns:
		ids := make([]ent.Value, 0, len(m.removedruns))
		for id := range m.removedruns {
			ids = append(ids, id)
		}
		return ids
	case audit.EdgeIssues:
		ids := make([]ent.Value, 0, len(m.removedissues))
		for id := range m.removedissues {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AuditMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedruns {
		edges = append(edges, audit.EdgeRuns)
	}
	if m.clearedissues {
		edges = append(edges, audit.EdgeIssues)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AuditMutation) EdgeCleared(name string) bool {
	switch name {
	case audit.EdgeRuns:
		return m.clearedruns
	case audit.EdgeIssues:
		return m.clearedissues
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AuditMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Audit unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AuditMutation) ResetEdge(name string) error {
	switch name {
	case audit.EdgeRuns:
		m.ResetRuns()
		return nil
	case audit.EdgeIssues:
		m.ResetIssues()
		return nil
	}
	return fmt.Errorf("unknown Audit edge %s", name)
}

// AuditRunMutation represents an operation that mutates the AuditRun nodes in the graph.
type AuditRunMutation struct {
	config
	op            Op
	typ           string
	id            *int
	status        *string
	actual_value  *string
	error_message *string
	started_at    *time.Time
	completed_at  *time.Time
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	audit         *int
	clearedaudit  bool
	issues        map[int]struct{}
	removedissues map[int]struct{}
	clearedissues bool
	done          bool
	oldValue      func(context.Context) (*AuditRun, error)
	predicates    []predicate.AuditRun
}

var _ ent.Mutation = (*AuditRunMutation)(nil)

// auditrunOption allows management of the mutation configuration using functional options.
type auditrunOption func(*AuditRunMutation)

// newAuditRunMutation creates new mutation for the AuditRun entity.
func newAuditRunMutation(c config, op Op, opts ...auditrunOption) *AuditRunMutation {
	m := &AuditRunMutation{
		config:        c,
		op:            op,
		typ:           TypeAuditRun,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAuditRunID sets the ID field of the mutation.
func withAuditRunID(id int) auditrunOption {
	return func(m *AuditRunMutation) {
		var (
			err   error
			once  sync.Once
			value *AuditRun
		)
		m.oldValue = func(ctx context.Context) (*AuditRun, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AuditRun.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAuditRun sets the old AuditRun of the mutation.
func withAuditRun(node *AuditRun) auditrunOption {
	return func(m *AuditRunMutation) {
		m.oldValue = func(context.Context) (*AuditRun, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AuditRunMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AuditRunMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AuditRunMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AuditRunMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AuditRun.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAuditID sets the "audit_id" field.
func (m *AuditRunMutation) SetAuditID(i int) {
	m.audit = &i
}

// AuditID returns the value of the "audit_id" field in the mutation.
func (m *AuditRunMutation) AuditID() (r int, exists bool) {
	v := m.audit
	if v == nil {
		return
	}
	return *v, true
}

// OldAuditID returns the old "audit_id" field's value of the AuditRun entity.
// If the AuditRun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditRunMutation) OldAuditID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuditID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuditID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuditID: %w", err)
	}
	return oldValue.AuditID, nil
}

// ResetAuditID resets all changes to the "audit_id" field.
func (m *AuditRunMutation) ResetAuditID() {
	m.audit = nil
}

// SetStatus sets the "status" field.
func (m *AuditRunMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *AuditRunMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the AuditRun entity.
// If the AuditRun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditRunMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *AuditRunMutation) ResetStatus() {
	m.status = nil
}

// SetActualValue sets the "actual_value" field.
func (m *AuditRunMutation) SetActualValue(s string) {
	m.actual_value = &s
}

// ActualValue returns the value of the "actual_value" field in the mutation.
func (m *AuditRunMutation) ActualValue() (r string, exists bool) {
	v := m.actual_value
	if v == nil {
		return
	}
	return *v, true
}

// OldActualValue returns the old "actual_value" field's value of the AuditRun entity.
// If the AuditRun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditRunMutation) OldActualValue(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActualValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActualValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActualValue: %w", err)
	}
	return oldValue.ActualValue, nil
}

// ClearActualValue clears the value of the "actual_value" field.
func (m *AuditRunMutation) ClearActualValue() {
	m.actual_value = nil
	m.clearedFields[auditrun.FieldActualValue] = struct{}{}
}

// ActualValueCleared returns if the "actual_value" field was cleared in this mutation.
func (m *AuditRunMutation) ActualValueCleared() bool {
	_, ok := m.clearedFields[auditrun.FieldActualValue]
	return ok
}

// ResetActualValue resets all changes to the "actual_value" field.
func (m *AuditRunMutation) ResetActualValue() {
	m.actual_value = nil
	delete(m.clearedFields, auditrun.FieldActualValue)
}

// SetErrorMessage sets the "error_message" field.
func (m *AuditRunMutation) SetErrorMessage(s string) {
	m.error_message = &s
}

// ErrorMessage returns the value of the "error_message" field in the mutation.
func (m *AuditRunMutation) ErrorMessage() (r string, exists bool) {
	v := m.error_message
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorMessage returns the old "error_message" field's value of the AuditRun entity.
// If the AuditRun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditRunMutation) OldErrorMessage(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorMessage: %w", err)
	}
	return oldValue.ErrorMessage, nil
}

// ClearErrorMessage clears the value of the "error_message" field.
func (m *AuditRunMutation) ClearErrorMessage() {
	m.error_message = nil
	m.clearedFields[auditrun.FieldErrorMessage] = struct{}{}
}

// ErrorMessageCleared returns if the "error_message" field was cleared in this mutation.
func (m *AuditRunMutation) ErrorMessageCleared() bool {
	_, ok := m.clearedFields[auditrun.FieldErrorMessage]
	return ok
}

// ResetErrorMessage resets all changes to the "error_message" field.
func (m *AuditRunMutation) ResetErrorMessage() {
	m.error_message = nil
	delete(m.clearedFields, auditrun.FieldErrorMessage)
}

// SetStartedAt sets the "started_at" field.
func (m *AuditRunMutation) SetStartedAt(t time.Time) {
	m.started_at = &t
}

// StartedAt returns the value of the "started_at" field in the mutation.
func (m *AuditRunMutation) StartedAt() (r time.Time, exists bool) {
	v := m.started_at
	if v == nil {
		return
	}
	return *v, true
}

// OldStartedAt returns the old "started_at" field's value of the AuditRun entity.
// If the AuditRun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditRunMutation) OldStartedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartedAt: %w", err)
	}
	return oldValue.StartedAt, nil
}

// ResetStartedAt resets all changes to the "started_at" field.
func (m *AuditRunMutation) ResetStartedAt() {
	m.started_at = nil
}

// SetCompletedAt sets the "completed_at" field.
func (m *AuditRunMutation) SetCompletedAt(t time.Time) {
	m.completed_at = &t
}

// CompletedAt returns the value of the "completed_at" field in the mutation.
func (m *AuditRunMutation) CompletedAt() (r time.Time, exists bool) {
	v := m.completed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCompletedAt returns the old "completed_at" field's value of the AuditRun entity.
// If the AuditRun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditRunMutation) OldCompletedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCompletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCompletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCompletedAt: %w", err)
	}
	return oldValue.CompletedAt, nil
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (m *AuditRunMutation) ClearCompletedAt() {
	m.completed_at = nil
	m.clearedFields[auditrun.FieldCompletedAt] = struct{}{}
}

// CompletedAtCleared returns if the "completed_at" field was cleared in this mutation.
func (m *AuditRunMutation) CompletedAtCleared() bool {
	_, ok := m.clearedFields[auditrun.FieldCompletedAt]
	return ok
}

// ResetCompletedAt resets all changes to the "completed_at" field.
func (m *AuditRunMutation) ResetCompletedAt() {
	m.completed_at = nil
	delete(m.clearedFields, auditrun.FieldCompletedAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *AuditRunMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AuditRunMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AuditRun entity.
// If the AuditRun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditRunMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AuditRunMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AuditRunMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AuditRunMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the AuditRun entity.
// If the AuditRun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditRunMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AuditRunMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// ClearAudit clears the "audit" edge to the Audit entity.
func (m *AuditRunMutation) ClearAudit() {
	m.clearedaudit = true
	m.clearedFields[auditrun.FieldAuditID] = struct{}{}
}

// AuditCleared reports if the "audit" edge to the Audit entity was cleared.
func (m *AuditRunMutation) AuditCleared() bool {
	return m.clearedaudit
}

// AuditIDs returns the "audit" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AuditID instead. It exists only for internal usage by the builders.
func (m *AuditRunMutation) AuditIDs() (ids []int) {
	if id := m.audit; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAudit resets all changes to the "audit" edge.
func (m *AuditRunMutation) ResetAudit() {
	m.audit = nil
	m.clearedaudit = false
}

// AddIssueIDs adds the "issues" edge to the Issue entity by ids.
func (m *AuditRunMutation) AddIssueIDs(ids ...int) {
	if m.issues == nil {
		m.issues = make(map[int]struct{})
	}
	for i := range ids {
		m.issues[ids[i]] = struct{}{}
	}
}

// ClearIssues clears the "issues" edge to the Issue entity.
func (m *AuditRunMutation) ClearIssues() {
	m.clearedissues = true
}

// IssuesCleared reports if the "issues" edge to the Issue entity was cleared.
func (m *AuditRunMutation) IssuesCleared() bool {
	return m.clearedissues
}

// RemoveIssueIDs removes the "issues" edge to the Issue entity by IDs.
func (m *AuditRunMutation) RemoveIssueIDs(ids ...int) {
	if m.removedissues == nil {
		m.removedissues = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.issues, ids[i])
		m.removedissues[ids[i]] = struct{}{}
	}
}

// RemovedIssues returns the removed IDs of the "issues" edge to the Issue entity.
func (m *AuditRunMutation) RemovedIssuesIDs() (ids []int) {
	for id := range m.removedissues {
		ids = append(ids, id)
	}
	return
}

// IssuesIDs returns the "issues" edge IDs in the mutation.
func (m *AuditRunMutation) IssuesIDs() (ids []int) {
	for id := range m.issues {
		ids = append(ids, id)
	}
	return
}

// ResetIssues resets all changes to the "issues" edge.
func (m *AuditRunMutation) ResetIssues() {
	m.issues = nil
	m.clearedissues = false
	m.removedissues = nil
}

// Where appends a list predicates to the AuditRunMutation builder.
func (m *AuditRunMutation) Where(ps ...predicate.AuditRun) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AuditRunMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AuditRunMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AuditRun, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AuditRunMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AuditRunMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AuditRun).
func (m *AuditRunMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AuditRunMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.audit != nil {
		fields = append(fields, auditrun.FieldAuditID)
	}
	if m.status != nil {
		fields = append(fields, auditrun.FieldStatus)
	}
	if m.actual_value != nil {
		fields = append(fields, auditrun.FieldActualValue)
	}
	if m.error_message != nil {
		fields = append(fields, auditrun.FieldErrorMessage)
	}
	if m.started_at != nil {
		fields = append(fields, auditrun.FieldStartedAt)
	}
	if m.completed_at != nil {
		fields = append(fields, auditrun.FieldCompletedAt)
	}
	if m.created_at != nil {
		fields = append(fields, auditrun.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, auditrun.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AuditRunMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case auditrun.FieldAuditID:
		return m.AuditID()
	case auditrun.FieldStatus:
		return m.Status()
	case auditrun.FieldActualValue:
		return m.ActualValue()
	case auditrun.FieldErrorMessage:
		return m.ErrorMessage()
	case auditrun.FieldStartedAt:
		return m.StartedAt()
	case auditrun.FieldCompletedAt:
		return m.CompletedAt()
	case auditrun.FieldCreatedAt:
		return m.CreatedAt()
	case auditrun.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AuditRunMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case auditrun.FieldAuditID:
		return m.OldAuditID(ctx)
	case auditrun.FieldStatus:
		return m.OldStatus(ctx)
	case auditrun.FieldActualValue:
		return m.OldActualValue(ctx)
	case auditrun.FieldErrorMessage:
		return m.OldErrorMessage(ctx)
	case auditrun.FieldStartedAt:
		return m.OldStartedAt(ctx)
	case auditrun.FieldCompletedAt:
		return m.OldCompletedAt(ctx)
	case auditrun.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case auditrun.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AuditRun field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditRunMutation) SetField(name string, value ent.Value) error {
	switch name {
	case auditrun.FieldAuditID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuditID(v)
		return nil
	case auditrun.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case auditrun.FieldActualValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActualValue(v)
		return nil
	case auditrun.FieldErrorMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorMessage(v)
		return nil
	case auditrun.FieldStartedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartedAt(v)
		return nil
	case auditrun.FieldCompletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCompletedAt(v)
		return nil
	case auditrun.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case auditrun.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AuditRun field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AuditRunMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AuditRunMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditRunMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AuditRun numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AuditRunMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(auditrun.FieldActualValue) {
		fields = append(fields, auditrun.FieldActualValue)
	}
	if m.FieldCleared(auditrun.FieldErrorMessage) {
		fields = append(fields, auditrun.FieldErrorMessage)
	}
	if m.FieldCleared(auditrun.FieldCompletedAt) {
		fields = append(fields, auditrun.FieldCompletedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AuditRunMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AuditRunMutation) ClearField(name string) error {
	switch name {
	case auditrun.FieldActualValue:
		m.ClearActualValue()
		return nil
	case auditrun.FieldErrorMessage:
		m.ClearErrorMessage()
		return nil
	case auditrun.FieldCompletedAt:
		m.ClearCompletedAt()
		return nil
	}
	return fmt.Errorf("unknown AuditRun nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AuditRunMutation) ResetField(name string) error {
	switch name {
	case auditrun.FieldAuditID:
		m.ResetAuditID()
		return nil
	case auditrun.FieldStatus:
		m.ResetStatus()
		return nil
	case auditrun.FieldActualValue:
		m.ResetActualValue()
		return nil
	case auditrun.FieldErrorMessage:
		m.ResetErrorMessage()
		return nil
	case auditrun.FieldStartedAt:
		m.ResetStartedAt()
		return nil
	case auditrun.FieldCompletedAt:
		m.ResetCompletedAt()
		return nil
	case auditrun.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case auditrun.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown AuditRun field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AuditRunMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.audit != nil {
		edges = append(edges, auditrun.EdgeAudit)
	}
	if m.issues != nil {
		edges = append(edges, auditrun.EdgeIssues)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AuditRunMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case auditrun.EdgeAudit:
		if id := m.audit; id != nil {
			return []ent.Value{*id}
		}
	case auditrun.EdgeIssues:
		ids := make([]ent.Value, 0, len(m.issues))
		for id := range m.issues {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AuditRunMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedissues != nil {
		edges = append(edges, auditrun.EdgeIssues)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AuditRunMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case auditrun.EdgeIssues:
		ids := make([]ent.Value, 0, len(m.removedissues))
		for id := range m.removedissues {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AuditRunMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedaudit {
		edges = append(edges, auditrun.EdgeAudit)
	}
	if m.clearedissues {
		edges = append(edges, auditrun.EdgeIssues)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AuditRunMutation) EdgeCleared(name string) bool {
	switch name {
	case auditrun.EdgeAudit:
		return m.clearedaudit
	case auditrun.EdgeIssues:
		return m.clearedissues
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AuditRunMutation) ClearEdge(name string) error {
	switch name {
	case auditrun.EdgeAudit:
		m.ClearAudit()
		return nil
	}
	return fmt.Errorf("unknown AuditRun unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AuditRunMutation) ResetEdge(name string) error {
	switch name {
	case auditrun.EdgeAudit:
		m.ResetAudit()
		return nil
	case auditrun.EdgeIssues:
		m.ResetIssues()
		return nil
	}
	return fmt.Errorf("unknown AuditRun edge %s", name)
}

// IssueMutation represents an operation that mutates the Issue nodes in the graph.
type IssueMutation struct {
	config
	op               Op
	typ              string
	id               *int
	expected_value   *string
	actual_value     *string
	description      *string
	created_at       *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	audit            *int
	clearedaudit     bool
	audit_run        *int
	clearedaudit_run bool
	done             bool
	oldValue         func(context.Context) (*Issue, error)
	predicates       []predicate.Issue
}

var _ ent.Mutation = (*IssueMutation)(nil)

// issueOption allows management of the mutation configuration using functional options.
type issueOption func(*IssueMutation)

// newIssueMutation creates new mutation for the Issue entity.
func newIssueMutation(c config, op Op, opts ...issueOption) *IssueMutation {
	m := &IssueMutation{
		config:        c,
		op:            op,
		typ:           TypeIssue,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withIssueID sets the ID field of the mutation.
func withIssueID(id int) issueOption {
	return func(m *IssueMutation) {
		var (
			err   error
			once  sync.Once
			value *Issue
		)
		m.oldValue = func(ctx context.Context) (*Issue, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Issue.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withIssue sets the old Issue of the mutation.
func withIssue(node *Issue) issueOption {
	return func(m *IssueMutation) {
		m.oldValue = func(context.Context) (*Issue, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m IssueMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m IssueMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *IssueMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *IssueMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Issue.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAuditID sets the "audit_id" field.
func (m *IssueMutation) SetAuditID(i int) {
	m.audit = &i
}

// AuditID returns the value of the "audit_id" field in the mutation.
func (m *IssueMutation) AuditID() (r int, exists bool) {
	v := m.audit
	if v == nil {
		return
	}
	return *v, true
}

// OldAuditID returns the old "audit_id" field's value of the Issue entity.
// If the Issue object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IssueMutation) OldAuditID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuditID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuditID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuditID: %w", err)
	}
	return oldValue.AuditID, nil
}

// ResetAuditID resets all changes to the "audit_id" field.
func (m *IssueMutation) ResetAuditID() {
	m.audit = nil
}

// SetAuditRunID sets the "audit_run_id" field.
func (m *IssueMutation) SetAuditRunID(i int) {
	m.audit_run = &i
}

// AuditRunID returns the value of the "audit_run_id" field in the mutation.
func (m *IssueMutation) AuditRunID() (r int, exists bool) {
	v := m.audit_run
	if v == nil {
		return
	}
	return *v, true
}

// OldAuditRunID returns the old "audit_run_id" field's value of the Issue entity.
// If the Issue object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IssueMutation) OldAuditRunID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuditRunID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuditRunID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuditRunID: %w", err)
	}
	return oldValue.AuditRunID, nil
}

// ResetAuditRunID resets all changes to the "audit_run_id" field.
func (m *IssueMutation) ResetAuditRunID() {
	m.audit_run = nil
}

// SetExpectedValue sets the "expected_value" field.
func (m *IssueMutation) SetExpectedValue(s string) {
	m.expected_value = &s
}

// ExpectedValue returns the value of the "expected_value" field in the mutation.
func (m *IssueMutation) ExpectedValue() (r string, exists bool) {
	v := m.expected_value
	if v == nil {
		return
	}
	return *v, true
}

// OldExpectedValue returns the old "expected_value" field's value of the Issue entity.
// If the Issue object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IssueMutation) OldExpectedValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpectedValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpectedValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpectedValue: %w", err)
	}
	return oldValue.ExpectedValue, nil
}

// ResetExpectedValue resets all changes to the "expected_value" field.
func (m *IssueMutation) ResetExpectedValue() {
	m.expected_value = nil
}

// SetActualValue sets the "actual_value" field.
func (m *IssueMutation) SetActualValue(s string) {
	m.actual_value = &s
}

// ActualValue returns the value of the "actual_value" field in the mutation.
func (m *IssueMutation) ActualValue() (r string, exists bool) {
	v := m.actual_value
	if v == nil {
		return
	}
	return *v, true
}

// OldActualValue returns the old "actual_value" field's value of the Issue entity.
// If the Issue object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IssueMutation) OldActualValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActualValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActualValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActualValue: %w", err)
	}
	return oldValue.ActualValue, nil
}

// ResetActualValue resets all changes to the "actual_value" field.
func (m *IssueMutation) ResetActualValue() {
	m.actual_value = nil
}

// SetDescription sets the "description" field.
func (m *IssueMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *IssueMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Issue entity.
// If the Issue object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IssueMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *IssueMutation) ResetDescription() {
	m.description = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *IssueMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *IssueMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Issue entity.
// If the Issue object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IssueMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *IssueMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *IssueMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *IssueMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Issue entity.
// If the Issue object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IssueMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *IssueMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// ClearAudit clears the "audit" edge to the Audit entity.
func (m *IssueMutation) ClearAudit() {
	m.clearedaudit = true
	m.clearedFields[issue.FieldAuditID] = struct{}{}
}

// AuditCleared reports if the "audit" edge to the Audit entity was cleared.
func (m *IssueMutation) AuditCleared() bool {
	return m.clearedaudit
}

// AuditIDs returns the "audit" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AuditID instead. It exists only for internal usage by the builders.
func (m *IssueMutation) AuditIDs() (ids []int) {
	if id := m.audit; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAudit resets all changes to the "audit" edge.
func (m *IssueMutation) ResetAudit() {
	m.audit = nil
	m.clearedaudit = false
}

// ClearAuditRun clears the "audit_run" edge to the AuditRun entity.
func (m *IssueMutation) ClearAuditRun() {
	m.clearedaudit_run = true
	m.clearedFields[issue.FieldAuditRunID] = struct{}{}
}

// AuditRunCleared reports if the "audit_run" edge to the AuditRun entity was cleared.
func (m *IssueMutation) AuditRunCleared() bool {
	return m.clearedaudit_run
}

// AuditRunIDs returns the "audit_run" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AuditRunID instead. It exists only for internal usage by the builders.
func (m *IssueMutation) AuditRunIDs() (ids []int) {
	if id := m.audit_run; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAuditRun resets all changes to the "audit_run" edge.
func (m *IssueMutation) ResetAuditRun() {
	m.audit_run = nil
	m.clearedaudit_run = false
}

// Where appends a list predicates to the IssueMutation builder.
func (m *IssueMutation) Where(ps ...predicate.Issue) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the IssueMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *IssueMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Issue, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *IssueMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *IssueMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Issue).
func (m *IssueMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *IssueMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.audit != nil {
		fields = append(fields, issue.FieldAuditID)
	}
	if m.audit_run != nil {
		fields = append(fields, issue.FieldAuditRunID)
	}
	if m.expected_value != nil {
		fields = append(fields, issue.FieldExpectedValue)
	}
	if m.actual_value != nil {
		fields = append(fields, issue.FieldActualValue)
	}
	if m.description != nil {
		fields = append(fields, issue.FieldDescription)
	}
	if m.created_at != nil {
		fields = append(fields, issue.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, issue.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *IssueMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case issue.FieldAuditID:
		return m.AuditID()
	case issue.FieldAuditRunID:
		return m.AuditRunID()
	case issue.FieldExpectedValue:
		return m.ExpectedValue()
	case issue.FieldActualValue:
		return m.ActualValue()
	case issue.FieldDescription:
		return m.Description()
	case issue.FieldCreatedAt:
		return m.CreatedAt()
	case issue.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *IssueMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case issue.FieldAuditID:
		return m.OldAuditID(ctx)
	case issue.FieldAuditRunID:
		return m.OldAuditRunID(ctx)
	case issue.FieldExpectedValue:
		return m.OldExpectedValue(ctx)
	case issue.FieldActualValue:
		return m.OldActualValue(ctx)
	case issue.FieldDescription:
		return m.OldDescription(ctx)
	case issue.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case issue.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Issue field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *IssueMutation) SetField(name string, value ent.Value) error {
	switch name {
	case issue.FieldAuditID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuditID(v)
		return nil
	case issue.FieldAuditRunID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuditRunID(v)
		return nil
	case issue.FieldExpectedValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpectedValue(v)
		return nil
	case issue.FieldActualValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActualValue(v)
		return nil
	case issue.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case issue.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case issue.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Issue field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *IssueMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *IssueMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *IssueMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Issue numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *IssueMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *IssueMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *IssueMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Issue nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *IssueMutation) ResetField(name string) error {
	switch name {
	case issue.FieldAuditID:
		m.ResetAuditID()
		return nil
	case issue.FieldAuditRunID:
		m.ResetAuditRunID()
		return nil
	case issue.FieldExpectedValue:
		m.ResetExpectedValue()
		return nil
	case issue.FieldActualValue:
		m.ResetActualValue()
		return nil
	case issue.FieldDescription:
		m.ResetDescription()
		return nil
	case issue.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case issue.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Issue field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *IssueMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.audit != nil {
		edges = append(edges, issue.EdgeAudit)
	}
	if m.audit_run != nil {
		edges = append(edges, issue.EdgeAuditRun)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *IssueMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case issue.EdgeAudit:
		if id := m.audit; id != nil {
			return []ent.Value{*id}
		}
	case issue.EdgeAuditRun:
		if id := m.audit_run; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *IssueMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *IssueMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *IssueMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedaudit {
		edges = append(edges, issue.EdgeAudit)
	}
	if m.clearedaudit_run {
		edges = append(edges, issue.EdgeAuditRun)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *IssueMutation) EdgeCleared(name string) bool {
	switch name {
	case issue.EdgeAudit:
		return m.clearedaudit
	case issue.EdgeAuditRun:
		return m.clearedaudit_run
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *IssueMutation) ClearEdge(name string) error {
	switch name {
	case issue.EdgeAudit:
		m.ClearAudit()
		return nil
	case issue.EdgeAuditRun:
		m.ClearAuditRun()
		return nil
	}
	return fmt.Errorf("unknown Issue unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *IssueMutation) ResetEdge(name string) error {
	switch name {
	case issue.EdgeAudit:
		m.ResetAudit()
		return nil
	case issue.EdgeAuditRun:
		m.ResetAuditRun()
		return nil
	}
	return fmt.Errorf("unknown Issue edge %s", name)
}

// VMInventoryMutation represents an operation that mutates the VMInventory nodes in the graph.
type VMInventoryMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	cpu           *int
	addcpu        *int
	memory        *int
	addmemory     *int
	power_state   *string
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*VMInventory, error)
	predicates    []predicate.VMInventory
}

var _ ent.Mutation = (*VMInventoryMutation)(nil)

// vminventoryOption allows management of the mutation configuration using functional options.
type vminventoryOption func(*VMInventoryMutation)

// newVMInventoryMutation creates new mutation for the VMInventory entity.
func newVMInventoryMutation(c config, op Op, opts ...vminventoryOption) *VMInventoryMutation {
	m := &VMInventoryMutation{
		config:        c,
		op:            op,
		typ:           TypeVMInventory,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withVMInventoryID sets the ID field of the mutation.
func withVMInventoryID(id int) vminventoryOption {
	return func(m *VMInventoryMutation) {
		var (
			err   error
			once  sync.Once
			value *VMInventory
		)
		m.oldValue = func(ctx context.Context) (*VMInventory, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().VMInventory.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withVMInventory sets the old VMInventory of the mutation.
func withVMInventory(node *VMInventory) vminventoryOption {
	return func(m *VMInventoryMutation) {
		m.oldValue = func(context.Context) (*VMInventory, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m VMInventoryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m VMInventoryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *VMInventoryMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *VMInventoryMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().VMInventory.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *VMInventoryMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *VMInventoryMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the VMInventory entity.
// If the VMInventory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VMInventoryMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *VMInventoryMutation) ResetName() {
	m.name = nil
}

// SetCPU sets the "cpu" field.
func (m *VMInventoryMutation) SetCPU(i int) {
	m.cpu = &i
	m.addcpu = nil
}

// CPU returns the value of the "cpu" field in the mutation.
func (m *VMInventoryMutation) CPU() (r int, exists bool) {
	v := m.cpu
	if v == nil {
		return
	}
	return *v, true
}

// OldCPU returns the old "cpu" field's value of the VMInventory entity.
// If the VMInventory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VMInventoryMutation) OldCPU(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCPU is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCPU requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCPU: %w", err)
	}
	return oldValue.CPU, nil
}

// AddCPU adds i to the "cpu" field.
func (m *VMInventoryMutation) AddCPU(i int) {
	if m.addcpu != nil {
		*m.addcpu += i
	} else {
		m.addcpu = &i
	}
}

// AddedCPU returns the value that was added to the "cpu" field in this mutation.
func (m *VMInventoryMutation) AddedCPU() (r int, exists bool) {
	v := m.addcpu
	if v == nil {
		return
	}
	return *v, true
}

// ResetCPU resets all changes to the "cpu" field.
func (m *VMInventoryMutation) ResetCPU() {
	m.cpu = nil
	m.addcpu = nil
}

// SetMemory sets the "memory" field.
func (m *VMInventoryMutation) SetMemory(i int) {
	m.memory = &i
	m.addmemory = nil
}

// Memory returns the value of the "memory" field in the mutation.
func (m *VMInventoryMutation) Memory() (r int, exists bool) {
	v := m.memory
	if v == nil {
		return
	}
	return *v, true
}

// OldMemory returns the old "memory" field's value of the VMInventory entity.
// If the VMInventory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VMInventoryMutation) OldMemory(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMemory is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMemory requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMemory: %w", err)
	}
	return oldValue.Memory, nil
}

// AddMemory adds i to the "memory" field.
func (m *VMInventoryMutation) AddMemory(i int) {
	if m.addmemory != nil {
		*m.addmemory += i
	} else {
		m.addmemory = &i
	}
}

// AddedMemory returns the value that was added to the "memory" field in this mutation.
func (m *VMInventoryMutation) AddedMemory() (r int, exists bool) {
	v := m.addmemory
	if v == nil {
		return
	}
	return *v, true
}

// ResetMemory resets all changes to the "memory" field.
func (m *VMInventoryMutation) ResetMemory() {
	m.memory = nil
	m.addmemory = nil
}

// SetPowerState sets the "power_state" field.
func (m *VMInventoryMutation) SetPowerState(s string) {
	m.power_state = &s
}

// PowerState returns the value of the "power_state" field in the mutation.
func (m *VMInventoryMutation) PowerState() (r string, exists bool) {
	v := m.power_state
	if v == nil {
		return
	}
	return *v, true
}

// OldPowerState returns the old "power_state" field's value of the VMInventory entity.
// If the VMInventory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VMInventoryMutation) OldPowerState(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPowerState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPowerState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPowerState: %w", err)
	}
	return oldValue.PowerState, nil
}

// ResetPowerState resets all changes to the "power_state" field.
func (m *VMInventoryMutation) ResetPowerState() {
	m.power_state = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *VMInventoryMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *VMInventoryMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the VMInventory entity.
// If the VMInventory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VMInventoryMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *VMInventoryMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *VMInventoryMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *VMInventoryMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the VMInventory entity.
// If the VMInventory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VMInventoryMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *VMInventoryMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the VMInventoryMutation builder.
func (m *VMInventoryMutation) Where(ps ...predicate.VMInventory) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the VMInventoryMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *VMInventoryMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.VMInventory, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *VMInventoryMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *VMInventoryMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (VMInventory).
func (m *VMInventoryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *VMInventoryMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, vminventory.FieldName)
	}
	if m.cpu != nil {
		fields = append(fields, vminventory.FieldCPU)
	}
	if m.memory != nil {
		fields = append(fields, vminventory.FieldMemory)
	}
	if m.power_state != nil {
		fields = append(fields, vminventory.FieldPowerState)
	}
	if m.created_at != nil {
		fields = append(fields, vminventory.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, vminventory.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *VMInventoryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case vminventory.FieldName:
		return m.Name()
	case vminventory.FieldCPU:
		return m.CPU()
	case vminventory.FieldMemory:
		return m.Memory()
	case vminventory.FieldPowerState:
		return m.PowerState()
	case vminventory.FieldCreatedAt:
		return m.CreatedAt()
	case vminventory.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *VMInventoryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case vminventory.FieldName:
		return m.OldName(ctx)
	case vminventory.FieldCPU:
		return m.OldCPU(ctx)
	case vminventory.FieldMemory:
		return m.OldMemory(ctx)
	case vminventory.FieldPowerState:
		return m.OldPowerState(ctx)
	case vminventory.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case vminventory.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown VMInventory field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VMInventoryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case vminventory.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case vminventory.FieldCPU:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCPU(v)
		return nil
	case vminventory.FieldMemory:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMemory(v)
		return nil
	case vminventory.FieldPowerState:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPowerState(v)
		return nil
	case vminventory.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case vminventory.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown VMInventory field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *VMInventoryMutation) AddedFields() []string {
	var fields []string
	if m.addcpu != nil {
		fields = append(fields, vminventory.FieldCPU)
	}
	if m.addmemory != nil {
		fields = append(fields, vminventory.FieldMemory)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *VMInventoryMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case vminventory.FieldCPU:
		return m.AddedCPU()
	case vminventory.FieldMemory:
		return m.AddedMemory()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VMInventoryMutation) AddField(name string, value ent.Value) error {
	switch name {
	case vminventory.FieldCPU:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCPU(v)
		return nil
	case vminventory.FieldMemory:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMemory(v)
		return nil
	}
	return fmt.Errorf("unknown VMInventory numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *VMInventoryMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *VMInventoryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *VMInventoryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown VMInventory nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *VMInventoryMutation) ResetField(name string) error {
	switch name {
	case vminventory.FieldName:
		m.ResetName()
		return nil
	case vminventory.FieldCPU:
		m.ResetCPU()
		return nil
	case vminventory.FieldMemory:
		m.ResetMemory()
		return nil
	case vminventory.FieldPowerState:
		m.ResetPowerState()
		return nil
	case vminventory.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case vminventory.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown VMInventory field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *VMInventoryMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *VMInventoryMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *VMInventoryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *VMInventoryMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *VMInventoryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *VMInventoryMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *VMInventoryMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown VMInventory unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *VMInventoryMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown VMInventory edge %s", name)
}
