// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/policyaudit"
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PolicyAuditUpdate is the builder for updating PolicyAudit entities.
type PolicyAuditUpdate struct {
	config
	hooks    []Hook
	mutation *PolicyAuditMutation
}

// Where appends a list predicates to the PolicyAuditUpdate builder.
func (_u *PolicyAuditUpdate) Where(ps ...predicate.PolicyAudit) *PolicyAuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PolicyAuditUpdate) SetName(v string) *PolicyAuditUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PolicyAuditUpdate) SetNillableName(v *string) *PolicyAuditUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAuditIds sets the "audit_ids" field.
func (_u *PolicyAuditUpdate) SetAuditIds(v []int) *PolicyAuditUpdate {
	_u.mutation.SetAuditIds(v)
	return _u
}

// AppendAuditIds appends value to the "audit_ids" field.
func (_u *PolicyAuditUpdate) AppendAuditIds(v []int) *PolicyAuditUpdate {
	_u.mutation.AppendAuditIds(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PolicyAuditUpdate) SetCreatedAt(v time.Time) *PolicyAuditUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PolicyAuditUpdate) SetNillableCreatedAt(v *time.Time) *PolicyAuditUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PolicyAuditUpdate) SetUpdatedAt(v time.Time) *PolicyAuditUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PolicyAuditMutation object of the builder.
func (_u *PolicyAuditUpdate) Mutation() *PolicyAuditMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PolicyAuditUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PolicyAuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyAuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PolicyAuditUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := policyaudit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicyAuditUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := policyaudit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PolicyAudit.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PolicyAuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policyaudit.Table, policyaudit.Columns, sqlgraph.NewFieldSpec(policyaudit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(policyaudit.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuditIds(); ok {
		_spec.SetField(policyaudit.FieldAuditIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuditIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, policyaudit.FieldAuditIds, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(policyaudit.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(policyaudit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policyaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PolicyAuditUpdateOne is the builder for updating a single PolicyAudit entity.
type PolicyAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PolicyAuditMutation
}

// SetName sets the "name" field.
func (_u *PolicyAuditUpdateOne) SetName(v string) *PolicyAuditUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PolicyAuditUpdateOne) SetNillableName(v *string) *PolicyAuditUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAuditIds sets the "audit_ids" field.
func (_u *PolicyAuditUpdateOne) SetAuditIds(v []int) *PolicyAuditUpdateOne {
	_u.mutation.SetAuditIds(v)
	return _u
}

// AppendAuditIds appends value to the "audit_ids" field.
func (_u *PolicyAuditUpdateOne) AppendAuditIds(v []int) *PolicyAuditUpdateOne {
	_u.mutation.AppendAuditIds(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PolicyAuditUpdateOne) SetCreatedAt(v time.Time) *PolicyAuditUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PolicyAuditUpdateOne) SetNillableCreatedAt(v *time.Time) *PolicyAuditUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PolicyAuditUpdateOne) SetUpdatedAt(v time.Time) *PolicyAuditUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PolicyAuditMutation object of the builder.
func (_u *PolicyAuditUpdateOne) Mutation() *PolicyAuditMutation {
	return _u.mutation
}

// Where appends a list predicates to the PolicyAuditUpdate builder.
func (_u *PolicyAuditUpdateOne) Where(ps ...predicate.PolicyAudit) *PolicyAuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PolicyAuditUpdateOne) Select(field string, fields ...string) *PolicyAuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PolicyAudit entity.
func (_u *PolicyAuditUpdateOne) Save(ctx context.Context) (*PolicyAudit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyAuditUpdateOne) SaveX(ctx context.Context) *PolicyAudit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PolicyAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyAuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PolicyAuditUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := policyaudit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicyAuditUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := policyaudit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PolicyAudit.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PolicyAuditUpdateOne) sqlSave(ctx context.Context) (_node *PolicyAudit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policyaudit.Table, policyaudit.Columns, sqlgraph.NewFieldSpec(policyaudit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PolicyAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, policyaudit.FieldID)
		for _, f := range fields {
			if !policyaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != policyaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(policyaudit.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuditIds(); ok {
		_spec.SetField(policyaudit.FieldAuditIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuditIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, policyaudit.FieldAuditIds, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(policyaudit.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(policyaudit.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PolicyAudit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policyaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
