// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/policyrun"
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PolicyRunUpdate is the builder for updating PolicyRun entities.
type PolicyRunUpdate struct {
	config
	hooks    []Hook
	mutation *PolicyRunMutation
}

// Where appends a list predicates to the PolicyRunUpdate builder.
func (_u *PolicyRunUpdate) Where(ps ...predicate.PolicyRun) *PolicyRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *PolicyRunUpdate) SetPolicyID(v int) *PolicyRunUpdate {
	_u.mutation.ResetPolicyID()
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *PolicyRunUpdate) SetNillablePolicyID(v *int) *PolicyRunUpdate {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// AddPolicyID adds value to the "policy_id" field.
func (_u *PolicyRunUpdate) AddPolicyID(v int) *PolicyRunUpdate {
	_u.mutation.AddPolicyID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PolicyRunUpdate) SetStatus(v string) *PolicyRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PolicyRunUpdate) SetNillableStatus(v *string) *PolicyRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuditRunIds sets the "audit_run_ids" field.
func (_u *PolicyRunUpdate) SetAuditRunIds(v []int) *PolicyRunUpdate {
	_u.mutation.SetAuditRunIds(v)
	return _u
}

// AppendAuditRunIds appends value to the "audit_run_ids" field.
func (_u *PolicyRunUpdate) AppendAuditRunIds(v []int) *PolicyRunUpdate {
	_u.mutation.AppendAuditRunIds(v)
	return _u
}

// ClearAuditRunIds clears the value of the "audit_run_ids" field.
func (_u *PolicyRunUpdate) ClearAuditRunIds() *PolicyRunUpdate {
	_u.mutation.ClearAuditRunIds()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *PolicyRunUpdate) SetStartedAt(v time.Time) *PolicyRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *PolicyRunUpdate) SetNillableStartedAt(v *time.Time) *PolicyRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PolicyRunUpdate) SetCompletedAt(v time.Time) *PolicyRunUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PolicyRunUpdate) SetNillableCompletedAt(v *time.Time) *PolicyRunUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PolicyRunUpdate) ClearCompletedAt() *PolicyRunUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the PolicyRunMutation object of the builder.
func (_u *PolicyRunUpdate) Mutation() *PolicyRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PolicyRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PolicyRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PolicyRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(policyrun.Table, policyrun.Columns, sqlgraph.NewFieldSpec(policyrun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PolicyID(); ok {
		_spec.SetField(policyrun.FieldPolicyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPolicyID(); ok {
		_spec.AddField(policyrun.FieldPolicyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(policyrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuditRunIds(); ok {
		_spec.SetField(policyrun.FieldAuditRunIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuditRunIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, policyrun.FieldAuditRunIds, value)
		})
	}
	if _u.mutation.AuditRunIdsCleared() {
		_spec.ClearField(policyrun.FieldAuditRunIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(policyrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(policyrun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(policyrun.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policyrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PolicyRunUpdateOne is the builder for updating a single PolicyRun entity.
type PolicyRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PolicyRunMutation
}

// SetPolicyID sets the "policy_id" field.
func (_u *PolicyRunUpdateOne) SetPolicyID(v int) *PolicyRunUpdateOne {
	_u.mutation.ResetPolicyID()
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *PolicyRunUpdateOne) SetNillablePolicyID(v *int) *PolicyRunUpdateOne {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// AddPolicyID adds value to the "policy_id" field.
func (_u *PolicyRunUpdateOne) AddPolicyID(v int) *PolicyRunUpdateOne {
	_u.mutation.AddPolicyID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PolicyRunUpdateOne) SetStatus(v string) *PolicyRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PolicyRunUpdateOne) SetNillableStatus(v *string) *PolicyRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuditRunIds sets the "audit_run_ids" field.
func (_u *PolicyRunUpdateOne) SetAuditRunIds(v []int) *PolicyRunUpdateOne {
	_u.mutation.SetAuditRunIds(v)
	return _u
}

// AppendAuditRunIds appends value to the "audit_run_ids" field.
func (_u *PolicyRunUpdateOne) AppendAuditRunIds(v []int) *PolicyRunUpdateOne {
	_u.mutation.AppendAuditRunIds(v)
	return _u
}

// ClearAuditRunIds clears the value of the "audit_run_ids" field.
func (_u *PolicyRunUpdateOne) ClearAuditRunIds() *PolicyRunUpdateOne {
	_u.mutation.ClearAuditRunIds()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *PolicyRunUpdateOne) SetStartedAt(v time.Time) *PolicyRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *PolicyRunUpdateOne) SetNillableStartedAt(v *time.Time) *PolicyRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PolicyRunUpdateOne) SetCompletedAt(v time.Time) *PolicyRunUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PolicyRunUpdateOne) SetNillableCompletedAt(v *time.Time) *PolicyRunUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PolicyRunUpdateOne) ClearCompletedAt() *PolicyRunUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the PolicyRunMutation object of the builder.
func (_u *PolicyRunUpdateOne) Mutation() *PolicyRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the PolicyRunUpdate builder.
func (_u *PolicyRunUpdateOne) Where(ps ...predicate.PolicyRun) *PolicyRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PolicyRunUpdateOne) Select(field string, fields ...string) *PolicyRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PolicyRun entity.
func (_u *PolicyRunUpdateOne) Save(ctx context.Context) (*PolicyRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyRunUpdateOne) SaveX(ctx context.Context) *PolicyRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PolicyRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PolicyRunUpdateOne) sqlSave(ctx context.Context) (_node *PolicyRun, err error) {
	_spec := sqlgraph.NewUpdateSpec(policyrun.Table, policyrun.Columns, sqlgraph.NewFieldSpec(policyrun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PolicyRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, policyrun.FieldID)
		for _, f := range fields {
			if !policyrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != policyrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PolicyID(); ok {
		_spec.SetField(policyrun.FieldPolicyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPolicyID(); ok {
		_spec.AddField(policyrun.FieldPolicyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(policyrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuditRunIds(); ok {
		_spec.SetField(policyrun.FieldAuditRunIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuditRunIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, policyrun.FieldAuditRunIds, value)
		})
	}
	if _u.mutation.AuditRunIdsCleared() {
		_spec.ClearField(policyrun.FieldAuditRunIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(policyrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(policyrun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(policyrun.FieldCompletedAt, field.TypeTime)
	}
	_node = &PolicyRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policyrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
