// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"security-central/ent/policyrun"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PolicyRun is the model entity for the PolicyRun schema.
type PolicyRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PolicyID holds the value of the "policy_id" field.
	PolicyID int `json:"policy_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AuditRunIds holds the value of the "audit_run_ids" field.
	AuditRunIds []int `json:"audit_run_ids,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PolicyRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case policyrun.FieldAuditRunIds:
			values[i] = new([]byte)
		case policyrun.FieldID, policyrun.FieldPolicyID:
			values[i] = new(sql.NullInt64)
		case policyrun.FieldStatus:
			values[i] = new(sql.NullString)
		case policyrun.FieldStartedAt, policyrun.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PolicyRun fields.
func (_m *PolicyRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case policyrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case policyrun.FieldPolicyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field policy_id", values[i])
			} else if value.Valid {
				_m.PolicyID = int(value.Int64)
			}
		case policyrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case policyrun.FieldAuditRunIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field audit_run_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AuditRunIds); err != nil {
					return fmt.Errorf("unmarshal field audit_run_ids: %w", err)
				}
			}
		case policyrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case policyrun.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PolicyRun.
// This includes values selected through modifiers, order, etc.
func (_m *PolicyRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PolicyRun.
// Note that you need to call PolicyRun.Unwrap() before calling this method if this PolicyRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PolicyRun) Update() *PolicyRunUpdateOne {
	return NewPolicyRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PolicyRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PolicyRun) Unwrap() *PolicyRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PolicyRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PolicyRun) String() string {
	var builder strings.Builder
	builder.WriteString("PolicyRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("policy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PolicyID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("audit_run_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuditRunIds))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PolicyRuns is a parsable slice of PolicyRun.
type PolicyRuns []*PolicyRun
