// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/policyaudit"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PolicyAuditCreate is the builder for creating a PolicyAudit entity.
type PolicyAuditCreate struct {
	config
	mutation *PolicyAuditMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PolicyAuditCreate) SetName(v string) *PolicyAuditCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAuditIds sets the "audit_ids" field.
func (_c *PolicyAuditCreate) SetAuditIds(v []int) *PolicyAuditCreate {
	_c.mutation.SetAuditIds(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PolicyAuditCreate) SetCreatedAt(v time.Time) *PolicyAuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PolicyAuditCreate) SetNillableCreatedAt(v *time.Time) *PolicyAuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PolicyAuditCreate) SetUpdatedAt(v time.Time) *PolicyAuditCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PolicyAuditCreate) SetNillableUpdatedAt(v *time.Time) *PolicyAuditCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PolicyAuditMutation object of the builder.
func (_c *PolicyAuditCreate) Mutation() *PolicyAuditMutation {
	return _c.mutation
}

// Save creates the PolicyAudit in the database.
func (_c *PolicyAuditCreate) Save(ctx context.Context) (*PolicyAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PolicyAuditCreate) SaveX(ctx context.Context) *PolicyAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PolicyAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PolicyAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PolicyAuditCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := policyaudit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := policyaudit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PolicyAuditCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PolicyAudit.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := policyaudit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PolicyAudit.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuditIds(); !ok {
		return &ValidationError{Name: "audit_ids", err: errors.New(`ent: missing required field "PolicyAudit.audit_ids"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PolicyAudit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PolicyAudit.updated_at"`)}
	}
	return nil
}

func (_c *PolicyAuditCreate) sqlSave(ctx context.Context) (*PolicyAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PolicyAuditCreate) createSpec() (*PolicyAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &PolicyAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(policyaudit.Table, sqlgraph.NewFieldSpec(policyaudit.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(policyaudit.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AuditIds(); ok {
		_spec.SetField(policyaudit.FieldAuditIds, field.TypeJSON, value)
		_node.AuditIds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(policyaudit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(policyaudit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PolicyAuditCreateBulk is the builder for creating many PolicyAudit entities in bulk.
type PolicyAuditCreateBulk struct {
	config
	err      error
	builders []*PolicyAuditCreate
}

// Save creates the PolicyAudit entities in the database.
func (_c *PolicyAuditCreateBulk) Save(ctx context.Context) ([]*PolicyAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PolicyAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PolicyAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PolicyAuditCreateBulk) SaveX(ctx context.Context) []*PolicyAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PolicyAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PolicyAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
