// Code generated by ent, DO NOT EDIT.

package ent

import (
	"security-central/ent/audit"
	"security-central/ent/auditrun"
	"security-central/ent/issue"
	"security-central/ent/policyaudit"
	"security-central/ent/policyrun"
	"security-central/ent/schema"
	"security-central/ent/vminventory"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditFields := schema.Audit{}.Fields()
	_ = auditFields
	// auditDescName is the schema descriptor for name field.
	auditDescName := auditFields[0].Descriptor()
	// audit.NameValidator is a validator for the "name" field. It is called by the builders before save.
	audit.NameValidator = auditDescName.Validators[0].(func(string) error)
	// auditDescCreatedAt is the schema descriptor for created_at field.
	auditDescCreatedAt := auditFields[2].Descriptor()
	// audit.DefaultCreatedAt holds the default value on creation for the created_at field.
	audit.DefaultCreatedAt = auditDescCreatedAt.Default.(func() time.Time)
	// auditDescUpdatedAt is the schema descriptor for updated_at field.
	auditDescUpdatedAt := auditFields[3].Descriptor()
	// audit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	audit.DefaultUpdatedAt = auditDescUpdatedAt.Default.(func() time.Time)
	// audit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	audit.UpdateDefaultUpdatedAt = auditDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditrunFields := schema.AuditRun{}.Fields()
	_ = auditrunFields
	// auditrunDescStatus is the schema descriptor for status field.
	auditrunDescStatus := auditrunFields[1].Descriptor()
	// auditrun.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	auditrun.StatusValidator = auditrunDescStatus.Validators[0].(func(string) error)
	// auditrunDescStartedAt is the schema descriptor for started_at field.
	auditrunDescStartedAt := auditrunFields[4].Descriptor()
	// auditrun.DefaultStartedAt holds the default value on creation for the started_at field.
	auditrun.DefaultStartedAt = auditrunDescStartedAt.Default.(func() time.Time)
	// auditrunDescCreatedAt is the schema descriptor for created_at field.
	auditrunDescCreatedAt := auditrunFields[6].Descriptor()
	// auditrun.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditrun.DefaultCreatedAt = auditrunDescCreatedAt.Default.(func() time.Time)
	// auditrunDescUpdatedAt is the schema descriptor for updated_at field.
	auditrunDescUpdatedAt := auditrunFields[7].Descriptor()
	// auditrun.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auditrun.DefaultUpdatedAt = auditrunDescUpdatedAt.Default.(func() time.Time)
	// auditrun.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auditrun.UpdateDefaultUpdatedAt = auditrunDescUpdatedAt.UpdateDefault.(func() time.Time)
	issueFields := schema.Issue{}.Fields()
	_ = issueFields
	// issueDescExpectedValue is the schema descriptor for expected_value field.
	issueDescExpectedValue := issueFields[3].Descriptor()
	// issue.ExpectedValueValidator is a validator for the "expected_value" field. It is called by the builders before save.
	issue.ExpectedValueValidator = issueDescExpectedValue.Validators[0].(func(string) error)
	// issueDescActualValue is the schema descriptor for actual_value field.
	issueDescActualValue := issueFields[4].Descriptor()
	// issue.ActualValueValidator is a validator for the "actual_value" field. It is called by the builders before save.
	issue.ActualValueValidator = issueDescActualValue.Validators[0].(func(string) error)
	// issueDescDescription is the schema descriptor for description field.
	issueDescDescription := issueFields[5].Descriptor()
	// issue.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	issue.DescriptionValidator = issueDescDescription.Validators[0].(func(string) error)
	// issueDescCreatedAt is the schema descriptor for created_at field.
	issueDescCreatedAt := issueFields[6].Descriptor()
	// issue.DefaultCreatedAt holds the default value on creation for the created_at field.
	issue.DefaultCreatedAt = issueDescCreatedAt.Default.(func() time.Time)
	// issueDescUpdatedAt is the schema descriptor for updated_at field.
	issueDescUpdatedAt := issueFields[7].Descriptor()
	// issue.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	issue.DefaultUpdatedAt = issueDescUpdatedAt.Default.(func() time.Time)
	// issue.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	issue.UpdateDefaultUpdatedAt = issueDescUpdatedAt.UpdateDefault.(func() time.Time)
	policyauditFields := schema.PolicyAudit{}.Fields()
	_ = policyauditFields
	// policyauditDescName is the schema descriptor for name field.
	policyauditDescName := policyauditFields[0].Descriptor()
	// policyaudit.NameValidator is a validator for the "name" field. It is called by the builders before save.
	policyaudit.NameValidator = policyauditDescName.Validators[0].(func(string) error)
	// policyauditDescCreatedAt is the schema descriptor for created_at field.
	policyauditDescCreatedAt := policyauditFields[2].Descriptor()
	// policyaudit.DefaultCreatedAt holds the default value on creation for the created_at field.
	policyaudit.DefaultCreatedAt = policyauditDescCreatedAt.Default.(func() time.Time)
	// policyauditDescUpdatedAt is the schema descriptor for updated_at field.
	policyauditDescUpdatedAt := policyauditFields[3].Descriptor()
	// policyaudit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	policyaudit.DefaultUpdatedAt = policyauditDescUpdatedAt.Default.(func() time.Time)
	// policyaudit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	policyaudit.UpdateDefaultUpdatedAt = policyauditDescUpdatedAt.UpdateDefault.(func() time.Time)
	policyrunFields := schema.PolicyRun{}.Fields()
	_ = policyrunFields
	// policyrunDescStatus is the schema descriptor for status field.
	policyrunDescStatus := policyrunFields[1].Descriptor()
	// policyrun.DefaultStatus holds the default value on creation for the status field.
	policyrun.DefaultStatus = policyrunDescStatus.Default.(string)
	// policyrunDescStartedAt is the schema descriptor for started_at field.
	policyrunDescStartedAt := policyrunFields[3].Descriptor()
	// policyrun.DefaultStartedAt holds the default value on creation for the started_at field.
	policyrun.DefaultStartedAt = policyrunDescStartedAt.Default.(func() time.Time)
	vminventoryFields := schema.VMInventory{}.Fields()
	_ = vminventoryFields
	// vminventoryDescName is the schema descriptor for name field.
	vminventoryDescName := vminventoryFields[0].Descriptor()
	// vminventory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	vminventory.NameValidator = vminventoryDescName.Validators[0].(func(string) error)
	// vminventoryDescCPU is the schema descriptor for cpu field.
	vminventoryDescCPU := vminventoryFields[1].Descriptor()
	// vminventory.CPUValidator is a validator for the "cpu" field. It is called by the builders before save.
	vminventory.CPUValidator = vminventoryDescCPU.Validators[0].(func(int) error)
	// vminventoryDescMemory is the schema descriptor for memory field.
	vminventoryDescMemory := vminventoryFields[2].Descriptor()
	// vminventory.MemoryValidator is a validator for the "memory" field. It is called by the builders before save.
	vminventory.MemoryValidator = vminventoryDescMemory.Validators[0].(func(int) error)
	// vminventoryDescPowerState is the schema descriptor for power_state field.
	vminventoryDescPowerState := vminventoryFields[3].Descriptor()
	// vminventory.DefaultPowerState holds the default value on creation for the power_state field.
	vminventory.DefaultPowerState = vminventoryDescPowerState.Default.(string)
	// vminventoryDescCreatedAt is the schema descriptor for created_at field.
	vminventoryDescCreatedAt := vminventoryFields[4].Descriptor()
	// vminventory.DefaultCreatedAt holds the default value on creation for the created_at field.
	vminventory.DefaultCreatedAt = vminventoryDescCreatedAt.Default.(func() time.Time)
	// vminventoryDescUpdatedAt is the schema descriptor for updated_at field.
	vminventoryDescUpdatedAt := vminventoryFields[5].Descriptor()
	// vminventory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vminventory.DefaultUpdatedAt = vminventoryDescUpdatedAt.Default.(func() time.Time)
	// vminventory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vminventory.UpdateDefaultUpdatedAt = vminventoryDescUpdatedAt.UpdateDefault.(func() time.Time)
}
