// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"security-central/ent/predicate"
	"security-central/ent/vminventory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VMInventoryDelete is the builder for deleting a VMInventory entity.
type VMInventoryDelete struct {
	config
	hooks    []Hook
	mutation *VMInventoryMutation
}

// Where appends a list predicates to the VMInventoryDelete builder.
func (_d *VMInventoryDelete) Where(ps ...predicate.VMInventory) *VMInventoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VMInventoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VMInventoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VMInventoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(vminventory.Table, sqlgraph.NewFieldSpec(vminventory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VMInventoryDeleteOne is the builder for deleting a single VMInventory entity.
type VMInventoryDeleteOne struct {
	_d *VMInventoryDelete
}

// Where appends a list predicates to the VMInventoryDelete builder.
func (_d *VMInventoryDeleteOne) Where(ps ...predicate.VMInventory) *VMInventoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VMInventoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{vminventory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VMInventoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
