// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"security-central/ent/vminventory"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VMInventoryCreate is the builder for creating a VMInventory entity.
type VMInventoryCreate struct {
	config
	mutation *VMInventoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *VMInventoryCreate) SetName(v string) *VMInventoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCPU sets the "cpu" field.
func (_c *VMInventoryCreate) SetCPU(v int) *VMInventoryCreate {
	_c.mutation.SetCPU(v)
	return _c
}

// SetMemory sets the "memory" field.
func (_c *VMInventoryCreate) SetMemory(v int) *VMInventoryCreate {
	_c.mutation.SetMemory(v)
	return _c
}

// SetPowerState sets the "power_state" field.
func (_c *VMInventoryCreate) SetPowerState(v string) *VMInventoryCreate {
	_c.mutation.SetPowerState(v)
	return _c
}

// SetNillablePowerState sets the "power_state" field if the given value is not nil.
func (_c *VMInventoryCreate) SetNillablePowerState(v *string) *VMInventoryCreate {
	if v != nil {
		_c.SetPowerState(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VMInventoryCreate) SetCreatedAt(v time.Time) *VMInventoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VMInventoryCreate) SetNillableCreatedAt(v *time.Time) *VMInventoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VMInventoryCreate) SetUpdatedAt(v time.Time) *VMInventoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VMInventoryCreate) SetNillableUpdatedAt(v *time.Time) *VMInventoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the VMInventoryMutation object of the builder.
func (_c *VMInventoryCreate) Mutation() *VMInventoryMutation {
	return _c.mutation
}

// Save creates the VMInventory in the database.
func (_c *VMInventoryCreate) Save(ctx context.Context) (*VMInventory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VMInventoryCreate) SaveX(ctx context.Context) *VMInventory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VMInventoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VMInventoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VMInventoryCreate) defaults() {
	if _, ok := _c.mutation.PowerState(); !ok {
		v := vminventory.DefaultPowerState
		_c.mutation.SetPowerState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vminventory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := vminventory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VMInventoryCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "VMInventory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := vminventory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VMInventory.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CPU(); !ok {
		return &ValidationError{Name: "cpu", err: errors.New(`ent: missing required field "VMInventory.cpu"`)}
	}
	if v, ok := _c.mutation.CPU(); ok {
		if err := vminventory.CPUValidator(v); err != nil {
			return &ValidationError{Name: "cpu", err: fmt.Errorf(`ent: validator failed for field "VMInventory.cpu": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Memory(); !ok {
		return &ValidationError{Name: "memory", err: errors.New(`ent: missing required field "VMInventory.memory"`)}
	}
	if v, ok := _c.mutation.Memory(); ok {
		if err := vminventory.MemoryValidator(v); err != nil {
			return &ValidationError{Name: "memory", err: fmt.Errorf(`ent: validator failed for field "VMInventory.memory": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PowerState(); !ok {
		return &ValidationError{Name: "power_state", err: errors.New(`ent: missing required field "VMInventory.power_state"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VMInventory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VMInventory.updated_at"`)}
	}
	return nil
}

func (_c *VMInventoryCreate) sqlSave(ctx context.Context) (*VMInventory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VMInventoryCreate) createSpec() (*VMInventory, *sqlgraph.CreateSpec) {
	var (
		_node = &VMInventory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vminventory.Table, sqlgraph.NewFieldSpec(vminventory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(vminventory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CPU(); ok {
		_spec.SetField(vminventory.FieldCPU, field.TypeInt, value)
		_node.CPU = value
	}
	if value, ok := _c.mutation.Memory(); ok {
		_spec.SetField(vminventory.FieldMemory, field.TypeInt, value)
		_node.Memory = value
	}
	if value, ok := _c.mutation.PowerState(); ok {
		_spec.SetField(vminventory.FieldPowerState, field.TypeString, value)
		_node.PowerState = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vminventory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vminventory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// VMInventoryCreateBulk is the builder for creating many VMInventory entities in bulk.
type VMInventoryCreateBulk struct {
	config
	err      error
	builders []*VMInventoryCreate
}

// Save creates the VMInventory entities in the database.
func (_c *VMInventoryCreateBulk) Save(ctx context.Context) ([]*VMInventory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VMInventory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VMInventoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VMInventoryCreateBulk) SaveX(ctx context.Context) []*VMInventory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VMInventoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VMInventoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
