// Code generated by ent, DO NOT EDIT.

package schedule

import (
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldID, id))
}

// TargetType applies equality check predicate on the "target_type" field. It's identical to TargetTypeEQ.
func TargetType(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldTargetType, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldTargetID, v))
}

// IntervalSeconds applies equality check predicate on the "interval_seconds" field. It's identical to IntervalSecondsEQ.
func IntervalSeconds(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldIntervalSeconds, v))
}

// NextRunAt applies equality check predicate on the "next_run_at" field. It's identical to NextRunAtEQ.
func NextRunAt(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldNextRunAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldCreatedAt, v))
}

// TargetTypeEQ applies the EQ predicate on the "target_type" field.
func TargetTypeEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldTargetType, v))
}

// TargetTypeNEQ applies the NEQ predicate on the "target_type" field.
func TargetTypeNEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldTargetType, v))
}

// TargetTypeIn applies the In predicate on the "target_type" field.
func TargetTypeIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldTargetType, vs...))
}

// TargetTypeNotIn applies the NotIn predicate on the "target_type" field.
func TargetTypeNotIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldTargetType, vs...))
}

// TargetTypeGT applies the GT predicate on the "target_type" field.
func TargetTypeGT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldTargetType, v))
}

// TargetTypeGTE applies the GTE predicate on the "target_type" field.
func TargetTypeGTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldTargetType, v))
}

// TargetTypeLT applies the LT predicate on the "target_type" field.
func TargetTypeLT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldTargetType, v))
}

// TargetTypeLTE applies the LTE predicate on the "target_type" field.
func TargetTypeLTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldTargetType, v))
}

// TargetTypeContains applies the Contains predicate on the "target_type" field.
func TargetTypeContains(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContains(FieldTargetType, v))
}

// TargetTypeHasPrefix applies the HasPrefix predicate on the "target_type" field.
func TargetTypeHasPrefix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasPrefix(FieldTargetType, v))
}

// TargetTypeHasSuffix applies the HasSuffix predicate on the "target_type" field.
func TargetTypeHasSuffix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasSuffix(FieldTargetType, v))
}

// TargetTypeEqualFold applies the EqualFold predicate on the "target_type" field.
func TargetTypeEqualFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEqualFold(FieldTargetType, v))
}

// TargetTypeContainsFold applies the ContainsFold predicate on the "target_type" field.
func TargetTypeContainsFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContainsFold(FieldTargetType, v))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldTargetID, vs...))
}

// TargetIDGT applies the GT predicate on the "target_id" field.
func TargetIDGT(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldTargetID, v))
}

// TargetIDGTE applies the GTE predicate on the "target_id" field.
func TargetIDGTE(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldTargetID, v))
}

// TargetIDLT applies the LT predicate on the "target_id" field.
func TargetIDLT(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldTargetID, v))
}

// TargetIDLTE applies the LTE predicate on the "target_id" field.
func TargetIDLTE(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldTargetID, v))
}

// IntervalSecondsEQ applies the EQ predicate on the "interval_seconds" field.
func IntervalSecondsEQ(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsNEQ applies the NEQ predicate on the "interval_seconds" field.
func IntervalSecondsNEQ(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsIn applies the In predicate on the "interval_seconds" field.
func IntervalSecondsIn(vs ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsNotIn applies the NotIn predicate on the "interval_seconds" field.
func IntervalSecondsNotIn(vs ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsGT applies the GT predicate on the "interval_seconds" field.
func IntervalSecondsGT(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldIntervalSeconds, v))
}

// IntervalSecondsGTE applies the GTE predicate on the "interval_seconds" field.
func IntervalSecondsGTE(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldIntervalSeconds, v))
}

// IntervalSecondsLT applies the LT predicate on the "interval_seconds" field.
func IntervalSecondsLT(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldIntervalSeconds, v))
}

// IntervalSecondsLTE applies the LTE predicate on the "interval_seconds" field.
func IntervalSecondsLTE(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldIntervalSeconds, v))
}

// NextRunAtEQ applies the EQ predicate on the "next_run_at" field.
func NextRunAtEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldNextRunAt, v))
}

// NextRunAtNEQ applies the NEQ predicate on the "next_run_at" field.
func NextRunAtNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldNextRunAt, v))
}

// NextRunAtIn applies the In predicate on the "next_run_at" field.
func NextRunAtIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldNextRunAt, vs...))
}

// NextRunAtNotIn applies the NotIn predicate on the "next_run_at" field.
func NextRunAtNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldNextRunAt, vs...))
}

// NextRunAtGT applies the GT predicate on the "next_run_at" field.
func NextRunAtGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldNextRunAt, v))
}

// NextRunAtGTE applies the GTE predicate on the "next_run_at" field.
func NextRunAtGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldNextRunAt, v))
}

// NextRunAtLT applies the LT predicate on the "next_run_at" field.
func NextRunAtLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldNextRunAt, v))
}

// NextRunAtLTE applies the LTE predicate on the "next_run_at" field.
func NextRunAtLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldNextRunAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.NotPredicates(p))
}
