// Code generated by ent, DO NOT EDIT.

package issue

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the issue type in the database.
	Label = "issue"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAuditID holds the string denoting the audit_id field in the database.
	FieldAuditID = "audit_id"
	// FieldAuditRunID holds the string denoting the audit_run_id field in the database.
	FieldAuditRunID = "audit_run_id"
	// FieldExpectedValue holds the string denoting the expected_value field in the database.
	FieldExpectedValue = "expected_value"
	// FieldActualValue holds the string denoting the actual_value field in the database.
	FieldActualValue = "actual_value"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAudit holds the string denoting the audit edge name in mutations.
	EdgeAudit = "audit"
	// EdgeAuditRun holds the string denoting the audit_run edge name in mutations.
	EdgeAuditRun = "audit_run"
	// Table holds the table name of the issue in the database.
	Table = "issues"
	// AuditTable is the table that holds the audit relation/edge.
	AuditTable = "issues"
	// AuditInverseTable is the table name for the Audit entity.
	// It exists in this package in order to avoid circular dependency with the "audit" package.
	AuditInverseTable = "audits"
	// AuditColumn is the table column denoting the audit relation/edge.
	AuditColumn = "audit_id"
	// AuditRunTable is the table that holds the audit_run relation/edge.
	AuditRunTable = "issues"
	// AuditRunInverseTable is the table name for the AuditRun entity.
	// It exists in this package in order to avoid circular dependency with the "auditrun" package.
	AuditRunInverseTable = "audit_runs"
	// AuditRunColumn is the table column denoting the audit_run relation/edge.
	AuditRunColumn = "audit_run_id"
)

// Columns holds all SQL columns for issue fields.
var Columns = []string{
	FieldID,
	FieldAuditID,
	FieldAuditRunID,
	FieldExpectedValue,
	FieldActualValue,
	FieldDescription,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ExpectedValueValidator is a validator for the "expected_value" field. It is called by the builders before save.
	ExpectedValueValidator func(string) error
	// ActualValueValidator is a validator for the "actual_value" field. It is called by the builders before save.
	ActualValueValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Issue queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAuditID orders the results by the audit_id field.
func ByAuditID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditID, opts...).ToFunc()
}

// ByAuditRunID orders the results by the audit_run_id field.
func ByAuditRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditRunID, opts...).ToFunc()
}

// ByExpectedValue orders the results by the expected_value field.
func ByExpectedValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedValue, opts...).ToFunc()
}

// ByActualValue orders the results by the actual_value field.
func ByActualValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualValue, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAuditField orders the results by audit field.
func ByAuditField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuditStep(), sql.OrderByField(field, opts...))
	}
}

// ByAuditRunField orders the results by audit_run field.
func ByAuditRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuditRunStep(), sql.OrderByField(field, opts...))
	}
}
func newAuditStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuditInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuditTable, AuditColumn),
	)
}
func newAuditRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuditRunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuditRunTable, AuditRunColumn),
	)
}
