// Code generated by ent, DO NOT EDIT.

package issue

import (
	"security-central/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Issue {
	return predicate.Issue(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Issue {
	return predicate.Issue(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Issue {
	return predicate.Issue(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Issue {
	return predicate.Issue(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Issue {
	return predicate.Issue(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Issue {
	return predicate.Issue(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Issue {
	return predicate.Issue(sql.FieldLTE(FieldID, id))
}

// AuditID applies equality check predicate on the "audit_id" field. It's identical to AuditIDEQ.
func AuditID(v int) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldAuditID, v))
}

// AuditRunID applies equality check predicate on the "audit_run_id" field. It's identical to AuditRunIDEQ.
func AuditRunID(v int) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldAuditRunID, v))
}

// ExpectedValue applies equality check predicate on the "expected_value" field. It's identical to ExpectedValueEQ.
func ExpectedValue(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldExpectedValue, v))
}

// ActualValue applies equality check predicate on the "actual_value" field. It's identical to ActualValueEQ.
func ActualValue(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldActualValue, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldUpdatedAt, v))
}

// AuditIDEQ applies the EQ predicate on the "audit_id" field.
func AuditIDEQ(v int) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldAuditID, v))
}

// AuditIDNEQ applies the NEQ predicate on the "audit_id" field.
func AuditIDNEQ(v int) predicate.Issue {
	return predicate.Issue(sql.FieldNEQ(FieldAuditID, v))
}

// AuditIDIn applies the In predicate on the "audit_id" field.
func AuditIDIn(vs ...int) predicate.Issue {
	return predicate.Issue(sql.FieldIn(FieldAuditID, vs...))
}

// AuditIDNotIn applies the NotIn predicate on the "audit_id" field.
func AuditIDNotIn(vs ...int) predicate.Issue {
	return predicate.Issue(sql.FieldNotIn(FieldAuditID, vs...))
}

// AuditRunIDEQ applies the EQ predicate on the "audit_run_id" field.
func AuditRunIDEQ(v int) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldAuditRunID, v))
}

// AuditRunIDNEQ applies the NEQ predicate on the "audit_run_id" field.
func AuditRunIDNEQ(v int) predicate.Issue {
	return predicate.Issue(sql.FieldNEQ(FieldAuditRunID, v))
}

// AuditRunIDIn applies the In predicate on the "audit_run_id" field.
func AuditRunIDIn(vs ...int) predicate.Issue {
	return predicate.Issue(sql.FieldIn(FieldAuditRunID, vs...))
}

// AuditRunIDNotIn applies the NotIn predicate on the "audit_run_id" field.
func AuditRunIDNotIn(vs ...int) predicate.Issue {
	return predicate.Issue(sql.FieldNotIn(FieldAuditRunID, vs...))
}

// ExpectedValueEQ applies the EQ predicate on the "expected_value" field.
func ExpectedValueEQ(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldExpectedValue, v))
}

// ExpectedValueNEQ applies the NEQ predicate on the "expected_value" field.
func ExpectedValueNEQ(v string) predicate.Issue {
	return predicate.Issue(sql.FieldNEQ(FieldExpectedValue, v))
}

// ExpectedValueIn applies the In predicate on the "expected_value" field.
func ExpectedValueIn(vs ...string) predicate.Issue {
	return predicate.Issue(sql.FieldIn(FieldExpectedValue, vs...))
}

// ExpectedValueNotIn applies the NotIn predicate on the "expected_value" field.
func ExpectedValueNotIn(vs ...string) predicate.Issue {
	return predicate.Issue(sql.FieldNotIn(FieldExpectedValue, vs...))
}

// ExpectedValueGT applies the GT predicate on the "expected_value" field.
func ExpectedValueGT(v string) predicate.Issue {
	return predicate.Issue(sql.FieldGT(FieldExpectedValue, v))
}

// ExpectedValueGTE applies the GTE predicate on the "expected_value" field.
func ExpectedValueGTE(v string) predicate.Issue {
	return predicate.Issue(sql.FieldGTE(FieldExpectedValue, v))
}

// ExpectedValueLT applies the LT predicate on the "expected_value" field.
func ExpectedValueLT(v string) predicate.Issue {
	return predicate.Issue(sql.FieldLT(FieldExpectedValue, v))
}

// ExpectedValueLTE applies the LTE predicate on the "expected_value" field.
func ExpectedValueLTE(v string) predicate.Issue {
	return predicate.Issue(sql.FieldLTE(FieldExpectedValue, v))
}

// ExpectedValueContains applies the Contains predicate on the "expected_value" field.
func ExpectedValueContains(v string) predicate.Issue {
	return predicate.Issue(sql.FieldContains(FieldExpectedValue, v))
}

// ExpectedValueHasPrefix applies the HasPrefix predicate on the "expected_value" field.
func ExpectedValueHasPrefix(v string) predicate.Issue {
	return predicate.Issue(sql.FieldHasPrefix(FieldExpectedValue, v))
}

// ExpectedValueHasSuffix applies the HasSuffix predicate on the "expected_value" field.
func ExpectedValueHasSuffix(v string) predicate.Issue {
	return predicate.Issue(sql.FieldHasSuffix(FieldExpectedValue, v))
}

// ExpectedValueEqualFold applies the EqualFold predicate on the "expected_value" field.
func ExpectedValueEqualFold(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEqualFold(FieldExpectedValue, v))
}

// ExpectedValueContainsFold applies the ContainsFold predicate on the "expected_value" field.
func ExpectedValueContainsFold(v string) predicate.Issue {
	return predicate.Issue(sql.FieldContainsFold(FieldExpectedValue, v))
}

// ActualValueEQ applies the EQ predicate on the "actual_value" field.
func ActualValueEQ(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldActualValue, v))
}

// ActualValueNEQ applies the NEQ predicate on the "actual_value" field.
func ActualValueNEQ(v string) predicate.Issue {
	return predicate.Issue(sql.FieldNEQ(FieldActualValue, v))
}

// ActualValueIn applies the In predicate on the "actual_value" field.
func ActualValueIn(vs ...string) predicate.Issue {
	return predicate.Issue(sql.FieldIn(FieldActualValue, vs...))
}

// ActualValueNotIn applies the NotIn predicate on the "actual_value" field.
func ActualValueNotIn(vs ...string) predicate.Issue {
	return predicate.Issue(sql.FieldNotIn(FieldActualValue, vs...))
}

// ActualValueGT applies the GT predicate on the "actual_value" field.
func ActualValueGT(v string) predicate.Issue {
	return predicate.Issue(sql.FieldGT(FieldActualValue, v))
}

// ActualValueGTE applies the GTE predicate on the "actual_value" field.
func ActualValueGTE(v string) predicate.Issue {
	return predicate.Issue(sql.FieldGTE(FieldActualValue, v))
}

// ActualValueLT applies the LT predicate on the "actual_value" field.
func ActualValueLT(v string) predicate.Issue {
	return predicate.Issue(sql.FieldLT(FieldActualValue, v))
}

// ActualValueLTE applies the LTE predicate on the "actual_value" field.
func ActualValueLTE(v string) predicate.Issue {
	return predicate.Issue(sql.FieldLTE(FieldActualValue, v))
}

// ActualValueContains applies the Contains predicate on the "actual_value" field.
func ActualValueContains(v string) predicate.Issue {
	return predicate.Issue(sql.FieldContains(FieldActualValue, v))
}

// ActualValueHasPrefix applies the HasPrefix predicate on the "actual_value" field.
func ActualValueHasPrefix(v string) predicate.Issue {
	return predicate.Issue(sql.FieldHasPrefix(FieldActualValue, v))
}

// ActualValueHasSuffix applies the HasSuffix predicate on the "actual_value" field.
func ActualValueHasSuffix(v string) predicate.Issue {
	return predicate.Issue(sql.FieldHasSuffix(FieldActualValue, v))
}

// ActualValueEqualFold applies the EqualFold predicate on the "actual_value" field.
func ActualValueEqualFold(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEqualFold(FieldActualValue, v))
}

// ActualValueContainsFold applies the ContainsFold predicate on the "actual_value" field.
func ActualValueContainsFold(v string) predicate.Issue {
	return predicate.Issue(sql.FieldContainsFold(FieldActualValue, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Issue {
	return predicate.Issue(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Issue {
	return predicate.Issue(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Issue {
	return predicate.Issue(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Issue {
	return predicate.Issue(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Issue {
	return predicate.Issue(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Issue {
	return predicate.Issue(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Issue {
	return predicate.Issue(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Issue {
	return predicate.Issue(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Issue {
	return predicate.Issue(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Issue {
	return predicate.Issue(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Issue {
	return predicate.Issue(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Issue {
	return predicate.Issue(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Issue {
	return predicate.Issue(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAudit applies the HasEdge predicate on the "audit" edge.
func HasAudit() predicate.Issue {
	return predicate.Issue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuditTable, AuditColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditWith applies the HasEdge predicate on the "audit" edge with a given conditions (other predicates).
func HasAuditWith(preds ...predicate.Audit) predicate.Issue {
	return predicate.Issue(func(s *sql.Selector) {
		step := newAuditStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuditRun applies the HasEdge predicate on the "audit_run" edge.
func HasAuditRun() predicate.Issue {
	return predicate.Issue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuditRunTable, AuditRunColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditRunWith applies the HasEdge predicate on the "audit_run" edge with a given conditions (other predicates).
func HasAuditRunWith(preds ...predicate.AuditRun) predicate.Issue {
	return predicate.Issue(func(s *sql.Selector) {
		step := newAuditRunStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Issue) predicate.Issue {
	return predicate.Issue(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Issue) predicate.Issue {
	return predicate.Issue(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Issue) predicate.Issue {
	return predicate.Issue(sql.NotPredicates(p))
}
