// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// AuditRun is the predicate function for auditrun builders.
type AuditRun func(*sql.Selector)

// Issue is the predicate function for issue builders.
type Issue func(*sql.Selector)

// VMInventory is the predicate function for vminventory builders.
type VMInventory func(*sql.Selector)
